package platformadmin

// Canonical permission codes. Must match platform_permission_catalog seed.
const (
	PermAdminAccess       = "admin.access"
	PermDashboardRead     = "dashboard.read"
	PermUsersRead         = "users.read"
	PermUsersSuspend      = "users.suspend"
	PermUsersBan          = "users.ban"
	PermUsersNotes        = "users.notes"
	PermUsersQuota        = "users.quota"
	PermUsersKeys         = "users.keys"
	PermUsersGDPR         = "users.gdpr"
	PermUsersForceLogout  = "users.force_logout"
	PermSegmentsRead      = "segments.read"
	PermEnterpriseRead    = "enterprise.read"
	PermEnterpriseWrite   = "enterprise.write"
	PermBillingRead       = "billing.read"
	PermBillingPlans      = "billing.plans"
	PermBillingSettings   = "billing.settings"
	PermBillingReceipts   = "billing.receipts"
	PermBillingCredits    = "billing.credits"
	PermBillingRevenue    = "billing.revenue"
	PermProductRead       = "product.read"
	PermProductWrite      = "product.write"
	PermAuthRead          = "auth.read"
	PermAuthWrite         = "auth.write"
	PermDenylistRead      = "denylist.read"
	PermDenylistWrite     = "denylist.write"
	PermChromeRead        = "chrome.read"
	PermChromeWrite       = "chrome.write"
	PermObservabilityRead = "observability.read"
	PermWebhooksReplay    = "webhooks.replay"
	PermDistributionRead  = "distribution.read"
	PermDistributionSync  = "distribution.sync"
	PermAuditRead         = "audit.read"
	PermAuditExport       = "audit.export"
	PermRBACRead          = "rbac.read"
	PermRBACWrite         = "rbac.write"
	PermAdminsInvite      = "admins.invite"
	PermAdminsBreakGlass  = "admins.break_glass"
	PermComplianceRead    = "compliance.read"
	PermComplianceWrite   = "compliance.write"
)
