import type { BillingInterval } from "@/stores/billing-ui";
import type { PaginationMeta } from "./common";

export type Plan = {
  id: string;
  display_name: string;
  description: string;
  plan_kind: string;
  plan_rank: number;
  currency_code: string;
  price_monthly_cents: number | null;
  price_yearly_cents: number | null;
  credits_monthly: number;
  per_seat: boolean;
  unlimited: boolean;
  popular: boolean;
  features: string[];
  sort_order: number;
  checkout_available: boolean;
  effective_cents: number | null;
  effective_interval: string;
  savings_percent?: number | null;
  savings_label?: string;
  upgrade_eligible?: boolean | null;
  can_proceed?: boolean | null;
  change_code?: string;
  change_reason?: string;
  change_label?: string;
  pending_label?: string;
};

export type PlansResponse = {
  interval: BillingInterval;
  money_locale?: string;
  settings: {
    annual_discount_percent: number;
    apply_paddle_discount_on_annual: boolean;
    paddle_discount_id: string | null;
    paddle_discount_code: string | null;
    default_currency: string;
    allow_downgrades: boolean;
    allow_cancel_at_period_end?: boolean;
    upgrade_proration_mode: string;
    auth_required_plan_message: string;
    auth_required_enterprise_message: string;
    enterprise_message_required: string;
    paddle_js_not_ready_message: string;
    checkout_price_missing_message: string;
    upgrade_missing_api_message: string;
    inquiry_missing_confirm_message: string;
    change_blocked_default_message: string;
    checkout_unavailable_message: string;
    upgrade_not_applied_message: string;
    checkout_request_failed_message: string;
    upgrade_request_failed_message: string;
    enterprise_inquiry_failed_message: string;
    plans_dialog_description: string;
    plans_dialog_upgrades_only_note?: string;
    topup_dialog_title?: string;
    topup_dialog_description?: string;
    topup_dialog_empty?: string;
    annual_toggle_label: string;
    monthly_toggle_label: string;
    enterprise_dialog_title: string;
    enterprise_dialog_description: string;
    enterprise_email_fallback: string;
    enterprise_company_label: string;
    enterprise_seats_label: string;
    enterprise_message_label: string;
    enterprise_company_placeholder: string;
    enterprise_seats_placeholder: string;
    enterprise_message_placeholder: string;
    enterprise_company_description?: string;
    enterprise_message_description?: string;
    enterprise_cancel_label: string;
    enterprise_send_label: string;
    enterprise_send_pending_label?: string;
    plans_load_failed_message: string;
    proration_review_hint: string;
    seat_quantity_hint: string;
    seat_quantity_label?: string;
    per_seat_one_fmt?: string;
    per_seat_many_fmt?: string;
    meta_sep?: string;
    max_seat_quantity?: number;
    min_seat_quantity?: number;
    default_seat_quantity?: number;
    default_checkout_quantity?: number;
    enterprise_message_rows?: number;
    date_range_months?: number;
    deep_target_token_min?: number;
    deep_target_token_max?: number;
    default_plan_interval?: BillingInterval;
    default_page_size?: number;
    max_page_size?: number;
    period_year_label: string;
    period_month_label: string;
    upgrade_confirm_title: string;
    upgrade_proration_mode_fmt: string;
    upgrade_plan_prefix: string;
    plans_dialog_title: string;
    active_plan_prefix: string;
    active_plan_expires_fmt: string;
    proration_prefix: string;
    upgrade_seats_fmt: string;
    upgrade_credit_prefix: string;
    upgrade_subtotal_prefix: string;
    upgrade_tax_prefix: string;
    upgrade_due_prefix: string;
    upgrade_preview_empty: string;
    upgrade_cancel_label: string;
    dialog_close_label?: string;
    unlimited_feature_label?: string;
  };
  plans: Plan[];
};

export type CheckoutSession = {
  action: "new_checkout" | "upgrade" | "upgrade_preview" | "blocked" | "same_plan" | string;
  code: string;
  message: string;
  plan_id: string;
  plan_display_name?: string;
  interval: BillingInterval;
  interval_label?: string;
  quantity: number;
  price_id?: string;
  discount_id?: string | null;
  discount_code?: string | null;
  custom_data?: Record<string, unknown>;
  currency_code?: string;
  display_cents?: number;
  proration_mode?: string;
  paddle_subscription_id?: string;
  proration_preview?: {
    currency_code?: string;
    subtotal?: string;
    tax?: string;
    credit?: string;
    balance?: string;
    grand_total?: string;
  } | null;
  pending_label?: string;
  action_label?: string;
};

export type SubscriptionStatus = {
  has_active_paid: boolean;
  is_expired: boolean;
  plan_tier: string;
  plan_tier_label?: string;
  plan_rank: number;
  billing_interval?: string;
  billing_interval_label?: string;
  status?: string;
  status_label: string;
  expires_at?: string;
  expires_at_label?: string;
  period_start?: string;
  period_end?: string;
  allow_downgrades: boolean;
  allow_cancel_at_period_end?: boolean;
  upgrade_proration_mode: string;
  downgrade_policy_message?: string;
  paddle_subscription_id?: string;
  primary_action_label: string;
  portal_action_label?: string;
  portal_pending_label?: string;
  portal_url_missing_message?: string;
  receipts_sync_action_label?: string;
  receipts_sync_pending_label?: string;
  avatar_sync_action_label?: string;
  avatar_sync_pending_label?: string;
  sign_out_action_label?: string;
  sign_out_pending_label?: string;
  account_delete_action_label?: string;
  account_delete_pending_label?: string;
  account_delete_confirm_message?: string;
  account_delete_failed_message?: string;
  page_eyebrow?: string;
  welcome_prefix?: string;
  welcome_guest?: string;
  page_description?: string;
  status_prefix?: string;
  tier_prefix?: string;
  interval_prefix?: string;
  renews_prefix?: string;
  nav_team_label?: string;
  nav_settings_label?: string;
  nav_traces_label?: string;
  nav_receipts_label?: string;
  nav_enterprise_label?: string;
  metric_plan_label?: string;
  metric_credits_label?: string;
  metric_topup_label?: string;
  metric_remaining_label?: string;
  metric_tokens_saved_label?: string;
  metric_tab_label?: string;
  metric_lines_added_label?: string;
  metric_lines_deleted_label?: string;
  quota_exhausted_title?: string;
  quota_exhausted_body?: string;
  buy_topup_label?: string;
  acceptance_hint?: string;
  chart_token_series_title?: string;
  chart_models_title?: string;
  chart_outcomes_title?: string;
  chart_modes_title?: string;
  traces_title?: string;
  receipts_title?: string;
  account_title?: string;
  avatar_hint?: string;
  delete_hint?: string;
  signed_in_prefix?: string;
  events_suffix?: string;
  meta_sep?: string;
  default_page_size?: number;
  avatar_sync_failed_message?: string;
  receipts_sync_failed_message?: string;
  traces_col_when?: string;
  traces_col_model?: string;
  traces_col_mode?: string;
  traces_col_tokens?: string;
  traces_col_latency?: string;
  receipts_col_date?: string;
  receipts_col_invoice?: string;
  receipts_col_status?: string;
  receipts_col_total?: string;
  receipts_col_view?: string;
  privacy_link_label?: string;
  terms_link_label?: string;
  path_dashboard?: string;
  path_team?: string;
  path_settings?: string;
  path_traces?: string;
  path_receipts?: string;
  path_enterprise?: string;
  path_receipts_prefix?: string;
  path_privacy?: string;
  path_terms?: string;
  path_home?: string;
  path_upgrade?: string;
  money_locale?: string;
};

export type ReceiptSummary = {
  id: string;
  paddle_transaction_id: string;
  paddle_invoice_number: string | null;
  paddle_invoice_pdf_url: string | null;
  display_id?: string;
  status: string;
  status_label?: string;
  currency_code: string;
  subtotal_cents: number;
  tax_cents: number;
  total_cents: number;
  bill_to_name: string | null;
  bill_to_email: string;
  bill_to_company: string | null;
  period_start: string | null;
  period_end: string | null;
  paid_at: string | null;
  created_at: string;
  date_label?: string;
};

export type PortalSessionResponse = {
  overview_url?: string;
  cancel_url?: string;
  cancel_disabled_message?: string;
  update_payment_url?: string;
  pending_label?: string;
  action_label?: string;
  error?: string;
};

export type ReceiptsListResponse = {
  items: ReceiptSummary[];
  meta: PaginationMeta;
  empty_message?: string;
  col_date?: string;
  col_invoice?: string;
  col_status?: string;
  col_total?: string;
  col_view?: string;
  open_action_label?: string;
  download_pdf_action_label?: string;
  download_pdf_failed_message?: string;
  download_pdf_done_message?: string;
  download_pdf_filename_fmt?: string;
  preview_field_description?: string;
  search_placeholder?: string;
  search_description?: string;
  q?: string;
  money_locale?: string;
  table_row_actions?: string;
  table_select_all?: string;
  table_select_row?: string;
  table_selected_fmt?: string;
  table_clear_selection?: string;
};

export type SyncReceiptsResponse = {
  synced: number;
  message: string;
  customer_id?: string;
  action_label?: string;
  pending_label?: string;
};
