-- Chrome for observability stats, distribution ranges, segment columns, plan price ids, auth toggles.
insert into public.site_messages (code, body) values
  ('ADMIN_OBS_TOTAL_EVENTS', 'Total events'),
  ('ADMIN_OBS_SUCCESS_24H', 'Success (24h)'),
  ('ADMIN_OBS_ERROR_24H', 'Errors (24h)'),
  ('ADMIN_OBS_TOKENS_BEFORE', 'Tokens before'),
  ('ADMIN_OBS_TOKENS_AFTER', 'Tokens after'),
  ('ADMIN_OBS_BY_MODE', 'By mode'),
  ('ADMIN_OBS_BY_MODEL', 'By model'),
  ('ADMIN_OBS_HEATMAP', 'Login countries'),
  ('ADMIN_OBS_WEBHOOKS', 'Webhook deliveries'),
  ('ADMIN_OBS_COL_EVENT_ID', 'Event id'),
  ('ADMIN_OBS_COL_EVENT_TYPE', 'Type'),
  ('ADMIN_OBS_COL_PROCESSED', 'Processed'),
  ('ADMIN_DIST_RANGE_DAY', 'Day'),
  ('ADMIN_DIST_RANGE_MONTH', 'Month'),
  ('ADMIN_DIST_RANGE_YEAR', 'Year'),
  ('ADMIN_DIST_COL_DAY', 'Day'),
  ('ADMIN_DIST_COL_SOURCE', 'Source'),
  ('ADMIN_DIST_COL_METRIC', 'Metric'),
  ('ADMIN_DIST_COL_COUNTRY', 'Country'),
  ('ADMIN_DIST_COL_VALUE', 'Value'),
  ('ADMIN_SEGMENT_COL_EMAIL', 'Email'),
  ('ADMIN_SEGMENT_COL_PLAN', 'Plan'),
  ('ADMIN_SEGMENT_COL_STATUS', 'Status'),
  ('ADMIN_SEGMENT_COL_COUNTRY', 'Country'),
  ('ADMIN_SEGMENT_COL_CREDITS', 'Credits'),
  ('ADMIN_SEGMENT_COL_NAME', 'Workspace'),
  ('ADMIN_SEGMENT_COL_SEATS', 'Seats'),
  ('ADMIN_SEGMENT_COL_MEMBERS', 'Members'),
  ('ADMIN_SEGMENT_COL_PENDING', 'Pending invites'),
  ('ADMIN_PLAN_PRICE_MONTHLY', 'Monthly price id (pri_*)'),
  ('ADMIN_PLAN_PRICE_YEARLY', 'Yearly price id (pri_*)'),
  ('ADMIN_PLAN_PRICE_TOPUP', 'Top-up price id (pri_*)'),
  ('ADMIN_AUTH_PROVIDERS_TITLE', 'Allowed providers'),
  ('ADMIN_AUTH_SCOPES_TITLE', 'OAuth scope chrome'),
  ('ADMIN_COMPLIANCE_EVENTS_TTL', 'Trim events TTL (days)'),
  ('ADMIN_COMPLIANCE_AUDIT_TTL', 'Audit log TTL (days)'),
  ('ADMIN_COMPLIANCE_REVIEW_TITLE', 'Access review'),
  ('ADMIN_ORIGIN_FORBIDDEN', 'Admin origin is not allowed for this API.'),
  ('ADMIN_RANGE_REQUIRED', 'Distribution range is required (day, month, or year).'),
  ('ADMIN_RANGE_INVALID', 'Distribution range must be day, month, or year.')
on conflict (code) do nothing;
