-- Landing value story: savings, simple token-cut flow, why Trim, how to use (marketing chrome).
insert into public.site_messages (code, body) values
  ('LANDING_HEADLINE', 'Cut LLM context by 80%. Keep the code that matters.'),
  ('LANDING_TAGLINE', 'Trim sits between your IDE and the model. It shrinks noisy prompts so you pay for signal, not vendor dumps and build logs.'),
  ('LANDING_HERO_NOTE', 'Runs on your machine. Cloud only handles login, quotas, and billing.'),
  ('LANDING_NAV_WHY', 'Why Trim'),
  ('LANDING_NAV_HOW', 'How it works'),
  ('LANDING_NAV_INSTALL', 'Install'),
  ('LANDING_STATS_TITLE', 'Less context. Lower bills.'),
  ('LANDING_STATS_SUBTITLE', 'Illustrative numbers for a heavy Cursor-style coding session. Your savings depend on how noisy the prompt is.'),
  ('LANDING_STAT_1_VALUE', '80%'),
  ('LANDING_STAT_1_LABEL', 'Fewer tokens sent to the model'),
  ('LANDING_STAT_2_VALUE', '5x'),
  ('LANDING_STAT_2_LABEL', 'More room for real work in the same budget'),
  ('LANDING_STAT_3_VALUE', '$'),
  ('LANDING_STAT_3_LABEL', 'USD saved on input tokens you never needed'),
  ('LANDING_STAT_3_HINT', 'Example: a $40 input bill can drop toward $8 when most of the prompt was noise.'),
  ('LANDING_FLOW_TITLE', 'How Trim shrinks a prompt (plain English)'),
  ('LANDING_FLOW_SUBTITLE', 'Not our secret sauce. Just the idea anyone can follow.'),
  ('LANDING_FLOW_1_TITLE', '1. Your IDE packs a huge bag'),
  ('LANDING_FLOW_1_BODY', 'Chat pulls open files, dependencies, logs, and past turns. Most of it is background noise.'),
  ('LANDING_FLOW_2_TITLE', '2. Trim sorts signal from clutter'),
  ('LANDING_FLOW_2_BODY', 'It keeps the functions you are editing and short outlines of the rest. Log spam and giant vendor files get cut down.'),
  ('LANDING_FLOW_3_TITLE', '3. The model sees a small, sharp prompt'),
  ('LANDING_FLOW_3_BODY', 'Same task. Far fewer tokens. You still get answers. You pay for less input.'),
  ('LANDING_FLOW_4_TITLE', '4. You see the savings'),
  ('LANDING_FLOW_4_BODY', 'Dashboard shows tokens trimmed and usage over time so the win is visible, not vibes.'),
  ('LANDING_WHY_TITLE', 'Why teams love Trim worldwide'),
  ('LANDING_WHY_SUBTITLE', 'Built for developers who live in Cursor, Copilot Chat, and agent workflows.'),
  ('LANDING_WHY_1_TITLE', 'Privacy by design'),
  ('LANDING_WHY_1_BODY', 'Trimming happens locally. We do not need your repo in our cloud to compress context.'),
  ('LANDING_WHY_2_TITLE', 'Works with the tools you already use'),
  ('LANDING_WHY_2_BODY', 'Point your IDE override base URL at Trim. No new editor. No migration project.'),
  ('LANDING_WHY_3_TITLE', 'Open-core and inspectable'),
  ('LANDING_WHY_3_BODY', 'Core proxy is open. You can read what runs on your laptop before you trust it.'),
  ('LANDING_WHY_4_TITLE', 'Fast Mode and Deep Mode'),
  ('LANDING_WHY_4_BODY', 'Start with instant AST heuristics. Turn on Deep Mode when you want heavier compression on your machine.'),
  ('LANDING_WHY_5_TITLE', 'Quotas and receipts in one place'),
  ('LANDING_WHY_5_BODY', 'Cloud meters usage, plans, and invoices so finance and engineering share the same story.'),
  ('LANDING_WHY_6_TITLE', 'Built for real agent traffic'),
  ('LANDING_WHY_6_BODY', 'Agents love dumping the world into context. Trim is for that world: noisy, repetitive, expensive.'),
  ('LANDING_WHY_7_TITLE', 'Windows, macOS, and Linux'),
  ('LANDING_WHY_7_BODY', 'Same install story everywhere. Your team does not need three different tools to save tokens.'),
  ('LANDING_WHY_8_TITLE', 'Model-agnostic savings'),
  ('LANDING_WHY_8_BODY', 'Works with OpenAI-compatible endpoints. Shrink input once; keep the same habit when you switch models.'),
  ('LANDING_WHY_9_TITLE', 'Faster turns, not just cheaper ones'),
  ('LANDING_WHY_9_BODY', 'Smaller prompts often mean less wait. You feel the win in latency as well as in the bill.'),
  ('LANDING_WHY_10_TITLE', 'Free to try, clear to upgrade'),
  ('LANDING_WHY_10_BODY', 'Install locally in a minute. Sign in when you want cloud metering, plans, and team receipts.'),
  ('LANDING_WHY_11_TITLE', 'Regulated-team friendly'),
  ('LANDING_WHY_11_BODY', 'Source stays on the laptop. Cloud sees auth, quotas, and billing, not your private repo dump.'),
  ('LANDING_WHY_12_TITLE', 'ROI you can show your manager'),
  ('LANDING_WHY_12_BODY', 'Tokens in, tokens out, percent cut, and USD direction. Finance understands the dashboard in one glance.'),
  ('LANDING_USE_TITLE', 'How to use it'),
  ('LANDING_USE_SUBTITLE', 'Three minutes from zero to smaller prompts.'),
  ('LANDING_USE_1_TITLE', 'Install the CLI'),
  ('LANDING_USE_1_BODY', 'One curl (or your package manager). Then run trim start.'),
  ('LANDING_USE_2_TITLE', 'Point your IDE at Trim'),
  ('LANDING_USE_2_BODY', 'In Cursor: Override Base URL -> http://localhost:8000/v1 (or your local port).'),
  ('LANDING_USE_3_TITLE', 'Keep coding'),
  ('LANDING_USE_3_BODY', 'Chat and agents go through Trim automatically. Check the dashboard for tokens saved.'),
  ('LANDING_INSTALL_TITLE', 'Install Trim'),
  ('LANDING_INSTALL_SUBTITLE', 'Local proxy first. Sign in when you want cloud metering and paid plans.'),
  ('LANDING_DEMO_TITLE', 'See exactly what Trim cuts'),
  ('LANDING_DEMO_SUBTITLE', 'Auto showcase of real prompt shapes. Hover to pause. Click a tab to jump.'),
  ('LANDING_DEMO_SAVED_FMT', '%s%% smaller prompt'),
  ('LANDING_DEMO_COST_HINT', 'Illustrative: 12.8k -> 2.1k tokens. At $3 / 1M input tokens that is about $0.038 -> $0.006 per turn (83% less USD on input).')
on conflict (code) do update set body = excluded.body;
