-- Admin KPI / checklist / action chrome (fail-closed: empty label hides UI).
insert into public.site_messages (code, body) values
  ('ADMIN_KPI_USERS_TOTAL', 'Users'),
  ('ADMIN_KPI_SUBSCRIPTIONS_ACTIVE', 'Active subscriptions'),
  ('ADMIN_KPI_EVENTS_24H', 'Events (24h)'),
  ('ADMIN_KPI_INSTALL_HITS_7D', 'Install hits (7d)'),
  ('ADMIN_KPI_ACTIVE_TODAY', 'Active today'),
  ('ADMIN_KPI_ACTIVE_7D', 'Active (7d)'),
  ('ADMIN_KPI_ACTIVE_30D', 'Active (30d)'),
  ('ADMIN_KPI_PAID_SEATS', 'Paid seats'),
  ('ADMIN_OPS_CHECKLIST_TITLE', 'Ops checklist'),
  ('ADMIN_CHECKLIST_STATUS_OK', 'ok'),
  ('ADMIN_CHECKLIST_STATUS_FAIL', 'fail'),
  ('ADMIN_HEALTH_POSTGRES', 'PostgreSQL'),
  ('ADMIN_HEALTH_REDIS', 'Redis'),
  ('ADMIN_RBAC_TAB_ROLES', 'Roles'),
  ('ADMIN_RBAC_TAB_PERMISSIONS', 'Permissions'),
  ('ADMIN_RBAC_TAB_ADMINS', 'Admins'),
  ('ADMIN_RBAC_CREATE_ROLE', 'Create role'),
  ('ADMIN_RBAC_INVITE_ADMIN', 'Invite admin'),
  ('ADMIN_DENYLIST_TAB_EMAIL', 'Email domains'),
  ('ADMIN_DENYLIST_TAB_IP', 'IP / CIDR'),
  ('ADMIN_DENYLIST_TAB_ASN', 'ASN'),
  ('ADMIN_ACTION_FORCE_LOGOUT', 'Force logout'),
  ('ADMIN_ACTION_REVOKE_KEYS', 'Revoke API keys'),
  ('ADMIN_ACTION_GDPR_EXPORT', 'GDPR export'),
  ('ADMIN_ACTION_GDPR_ERASE', 'GDPR erase'),
  ('ADMIN_BREAK_GLASS_APPROVE', 'Approve'),
  ('ADMIN_BREAK_GLASS_DENY', 'Deny'),
  ('ADMIN_USERS_COL_EMAIL', 'Email'),
  ('ADMIN_USERS_COL_STATUS', 'Status'),
  ('ADMIN_USERS_COL_PLAN', 'Plan'),
  ('ADMIN_USERS_COL_COUNTRY', 'Country'),
  ('ADMIN_ACTION_REMOVE', 'Remove'),
  ('ADMIN_ACTION_SAVE', 'Save'),
  ('ADMIN_ACTION_ADD', 'Add'),
  ('ADMIN_PLAN_ACTIVE', 'Active'),
  ('ADMIN_PLAN_PUBLIC', 'Public'),
  ('ADMIN_BILLING_PRICING_BOUND', 'Pricing bound'),
  ('ADMIN_BILLING_CANCEL_AT_PERIOD_END', 'Allow cancel at period end'),
  ('ADMIN_STEP_UP_VERIFY', 'Verify step-up'),
  ('ADMIN_ACTION_WEBHOOK_REPLAY', 'Replay webhook'),
  ('ADMIN_ACTION_CREDIT_GRANT', 'Grant credits')
on conflict (code) do nothing;
