-- Per-field admin form descriptions (replace generic ADMIN_SETTINGS_FIELD_DESC on settings forms).
insert into public.site_messages (code, body) values
  ('ADMIN_PLAN_ID_DESC', 'Stable plan identifier used in API, checkout, and Paddle sync. Cannot change after create.'),
  ('ADMIN_PLAN_NAME_DESC', 'Customer-facing plan title shown in pricing and the admin plans table.'),
  ('ADMIN_PLAN_CURRENCY_DESC', 'Default checkout currency comes from Billing settings; plan amounts use that ISO-4217 code.'),
  ('ADMIN_PLAN_PRICE_MONTHLY_DESC', 'Recurring monthly price in major currency units (for example 9.99). Stored as cents in the API.'),
  ('ADMIN_PLAN_PRICE_YEARLY_DESC', 'Recurring yearly price in major currency units. Stored as cents in the API.'),
  ('ADMIN_PLAN_ACTIVE_DESC', 'Inactive plans stay in the catalog but are not offered for new checkout.'),
  ('ADMIN_PLAN_KIND_DESC', 'Subscription, top-up, or enterprise plan type. Controls which Paddle prices apply.'),
  ('ADMIN_PLAN_INTERVAL_DESC', 'Default billing interval label for self-serve checkout when a plan supports both monthly and yearly.'),
  ('ADMIN_PLAN_DESCRIPTION_DESC', 'Longer marketing or internal description stored on the plan record.'),
  ('ADMIN_PLAN_RANK_DESC', 'Sort weight for plan ordering; higher ranks appear first where plans are listed.'),
  ('ADMIN_PLAN_SORT_ORDER_DESC', 'Secondary ordering index when ranks tie.'),
  ('ADMIN_PLAN_PUBLIC_DESC', 'Public plans appear in self-serve pricing; private plans are operator-only.'),
  ('ADMIN_PLAN_FEATURES_DESC', 'JSON feature flags or bullet list metadata attached to the plan.'),
  ('ADMIN_PLAN_SYNC_PADDLE_DESC', 'When enabled, save pushes product and price changes to Paddle.'),
  ('ADMIN_RBAC_ROLE_NAME_DESC', 'Human-readable role title shown to operators.'),
  ('ADMIN_RBAC_ROLE_SLUG_DESC', 'Stable slug referenced in permissions and audit logs.'),
  ('ADMIN_RBAC_PERMS_DESC', 'Toggle platform permissions granted to admins assigned this role.'),
  ('ADMIN_RBAC_INVITE_EMAIL_DESC', 'Email of the user to promote; they must already exist in auth.'),
  ('ADMIN_RBAC_INVITE_ROLE_DESC', 'Role assigned when the invite is accepted.'),
  ('ADMIN_CREDITS_USER_ID_DESC', 'Target account user id (UUID) receiving the manual grant.'),
  ('ADMIN_CREDITS_AMOUNT_DESC', 'Number of credits to add to the user balance (positive integer).'),
  ('ADMIN_CREDITS_REASON_DESC', 'Audit reason stored on the credit ledger row.'),
  ('ADMIN_BREAK_GLASS_PERM_DESC', 'Permission code temporarily elevated for this break-glass session.'),
  ('ADMIN_BREAK_GLASS_REASON_DESC', 'Operator justification recorded in audit for the elevation.'),
  ('ADMIN_DENYLIST_VALUE_DESC', 'Blocked value: email domain, IP CIDR, or ASN depending on the tab.'),
  ('ADMIN_DENYLIST_REASON_DESC', 'Why this entry was added; shown in audit and the denylist table.'),
  ('ADMIN_DISPUTE_TX_DESC', 'Paddle transaction id tying the dispute note to a receipt.'),
  ('ADMIN_DISPUTE_USER_DESC', 'Optional user id if the dispute is account-specific.'),
  ('ADMIN_RECEIPT_DISPUTE_REASON_DESC', 'Free-text dispute or chargeback note for operator tracking.'),
  ('ADMIN_DISPUTE_STATUS_DESC', 'Workflow status for the dispute note (open, watching, or closed).'),
  ('ADMIN_BILLING_CURRENCY_DESC', 'Default ISO-4217 currency for new Paddle prices and checkout.'),
  ('ADMIN_BILLING_DEFAULT_PAGE_SIZE_DESC', 'Default page size for admin billing list tables.'),
  ('ADMIN_BILLING_MAX_PAGE_SIZE_DESC', 'Hard cap on page size for billing API pagination.'),
  ('ADMIN_BILLING_SKIP_TO_MAX_DESC', 'Maximum pages a client may skip forward in one jump.'),
  ('ADMIN_BILLING_CHART_TOP_N_DESC', 'Number of top series shown on billing usage charts.'),
  ('ADMIN_BILLING_CHART_DAYS_DESC', 'Days of history included in billing chart series.'),
  ('ADMIN_BILLING_CHART_CACHE_TTL_DESC', 'Seconds to cache computed chart payloads in Redis.'),
  ('ADMIN_BILLING_DATE_RANGE_MONTHS_DESC', 'Months of history available in billing date-range filters.'),
  ('ADMIN_BILLING_PLAN_INTERVAL_DESC', 'Default interval preselected in self-serve plan change flows.'),
  ('ADMIN_BILLING_DEFAULT_SEATS_DESC', 'Seat quantity applied when a workspace has no explicit seat count.'),
  ('ADMIN_BILLING_MIN_SEATS_DESC', 'Minimum billable seats enforced at checkout and renewal.'),
  ('ADMIN_BILLING_DEEP_TARGET_DEFAULT_DESC', 'Default Deep Mode token target for new subscriptions.'),
  ('ADMIN_BILLING_DEEP_TARGET_MIN_DESC', 'Lower bound users may select for Deep token targets.'),
  ('ADMIN_BILLING_DEEP_TARGET_MAX_DESC', 'Upper bound users may select for Deep token targets.'),
  ('ADMIN_BILLING_PRORATION_MODE_DESC', 'How Paddle prorates mid-cycle subscription upgrades.'),
  ('ADMIN_BILLING_CANCEL_AT_PERIOD_END_DESC', 'Allow customers to schedule cancellation at period end.'),
  ('ADMIN_BILLING_ALLOW_DOWNGRADES_DESC', 'Allow self-serve plan downgrades when policy permits.'),
  ('ADMIN_BILLING_MONTHLY_TO_ANNUAL_DESC', 'Treat monthly-to-annual interval changes as upgrades.'),
  ('ADMIN_COMPLIANCE_EVENTS_TTL_DESC', 'Days to retain trim_events rows before automated purge.'),
  ('ADMIN_COMPLIANCE_AUDIT_TTL_DESC', 'Days to retain platform admin audit log entries.'),
  ('ADMIN_COMPLIANCE_AUDIT_EXPORT_MAX_DESC', 'Maximum audit rows returned in a single export job.'),
  ('ADMIN_COMPLIANCE_ATTEST_LIMIT_DESC', 'Maximum access-review attestation rows kept in history.'),
  ('ADMIN_COMPLIANCE_BREAK_GLASS_TTL_DESC', 'Minutes a break-glass elevation remains valid.'),
  ('ADMIN_COMPLIANCE_FORCE_LOGOUT_TTL_DESC', 'Seconds the force-logout marker blocks new sessions.'),
  ('ADMIN_COMPLIANCE_EVENTS_PARTITION_AHEAD_DESC', 'How many future months of trim_events partitions to pre-create.'),
  ('ADMIN_COMPLIANCE_EVENTS_PARTITION_ENSURE_SEC_DESC', 'Background interval that ensures trim_events partitions exist.'),
  ('ADMIN_ACCESS_REVIEW_PERIOD_DESC', 'Label for the access review period being attested (for example Q1 2026).'),
  ('ADMIN_ACCESS_REVIEW_NOTES_DESC', 'Optional notes stored on the attestation record.'),
  ('ADMIN_COMPLIANCE_ATTEST_REASON_DESC', 'Audit reason required when filing an access review attestation.'),
  ('ADMIN_PRODUCT_MODE_DESC', 'Default Fast compression mode for new accounts when unset in preferences.'),
  ('ADMIN_PRODUCT_ENGINE_DESC', 'Default Deep engine identifier used when Deep Mode is enabled.'),
  ('ADMIN_PRODUCT_TREESITTER_DESC', 'Require Tree-sitter parsing for supported languages in the compress pipeline.'),
  ('ADMIN_PRODUCT_DEEP_ATTACH_DESC', 'Default whether Deep Mode attaches full file context on first use.'),
  ('ADMIN_PRODUCT_MODEL_ROUTING_DESC', 'Enable routing compress requests across configured model providers.'),
  ('ADMIN_PRODUCT_RATE_IP_DESC', 'Maximum API requests per minute allowed per client IP.'),
  ('ADMIN_PRODUCT_RATE_USER_DESC', 'Maximum API requests per minute allowed per authenticated user.'),
  ('ADMIN_PRODUCT_POW_DESC', 'Proof-of-work difficulty for anonymous or abusive traffic (0 disables).'),
  ('ADMIN_PRODUCT_MAX_HW_DESC', 'Maximum distinct accounts allowed per hardware fingerprint.'),
  ('ADMIN_PRODUCT_MAX_JA4_DESC', 'Maximum distinct accounts allowed per JA4 TLS fingerprint.'),
  ('ADMIN_PRODUCT_CF_THREAT_DESC', 'Minimum Cloudflare threat score to treat traffic as suspicious.'),
  ('ADMIN_PRODUCT_CLI_NOTICE_DESC', 'Message shown to CLI clients below min_cli_version.'),
  ('ADMIN_PRODUCT_MIN_CLI_DESC', 'Semver floor; older CLI builds receive the force-upgrade notice.'),
  ('ADMIN_PRODUCT_CHURN_HIGH_USAGE_DESC', 'Usage ratio threshold marking high-risk churn segments.'),
  ('ADMIN_PRODUCT_CHURN_MED_USAGE_DESC', 'Usage ratio threshold for medium churn risk.'),
  ('ADMIN_PRODUCT_CHURN_HIGH_IDLE_DESC', 'Idle days threshold for high idle churn risk.'),
  ('ADMIN_PRODUCT_CHURN_LOW_IDLE_DESC', 'Idle days threshold for low idle churn risk.'),
  ('ADMIN_PRODUCT_FAST_BALANCED_MIN_DESC', 'Minimum source lines before balanced Fast mode applies strong trims.'),
  ('ADMIN_PRODUCT_FAST_AGGRESSIVE_MIN_DESC', 'Minimum source lines before aggressive Fast mode applies strong trims.'),
  ('ADMIN_PRODUCT_FAST_MILD_MIN_DESC', 'Minimum source lines before mild Fast mode applies log-focused trims.'),
  ('ADMIN_PRODUCT_QUEUE_WARN_DEPTH_DESC', 'Paddle webhook queue depth that triggers operator alerts.'),
  ('ADMIN_USER_QUOTA_LIMIT_DESC', 'Monthly credit allowance cap for this account (user_quotas.monthly_credit_limit).'),
  ('ADMIN_USER_QUOTA_TOPUP_DESC', 'Purchased top-up credits outside the monthly allowance (user_quotas.purchased_topup_credits).'),
  ('ADMIN_USER_CREDIT_AMOUNT_DESC', 'Number of credits to add to the user balance (positive integer).'),
  ('ADMIN_CHROME_CODE_DESC', 'Site message code in site_messages; identifies the row updated by the admin PATCH route.'),
  ('ADMIN_CHROME_BODY_DESC', 'String body stored in site_messages and served to clients after cache reload.'),
  ('ADMIN_LEGAL_BODY_DESC', 'Legal section content stored on the legal_docs row for this id.'),
  ('ADMIN_ENTERPRISE_STATUS_DESC', 'Inquiry workflow status (new, contacted, or closed).'),
  ('ADMIN_ENTERPRISE_MESSAGE_DESC', 'Internal contract or sales notes stored on the enterprise inquiry (contract_notes).'),
  ('ADMIN_ENTERPRISE_SEATS_DESC', 'Seat quantity offered in the proposal (offered_seat_quantity).'),
  ('ADMIN_EMAIL_TEMPLATE_BODY_DESC', 'Email template body text for this template code in site_messages.')
on conflict (code) do update
set body = excluded.body,
    updated_at = now();
