-- Shared DataTable column chrome for admin list pages formerly using ad-hoc markup.
insert into public.site_messages (code, body) values
  ('ADMIN_SUB_COL_EMAIL', 'Email'),
  ('ADMIN_SUB_COL_PLAN', 'Plan'),
  ('ADMIN_SUB_COL_STATUS', 'Status'),
  ('ADMIN_SUB_COL_PADDLE', 'Paddle id'),
  ('ADMIN_SUB_COL_EXPIRES', 'Expires'),
  ('ADMIN_AUDIT_COL_ACTION', 'Action'),
  ('ADMIN_AUDIT_COL_RESOURCE', 'Resource'),
  ('ADMIN_AUDIT_COL_ID', 'Resource id'),
  ('ADMIN_AUDIT_COL_WHEN', 'When'),
  ('ADMIN_DENYLIST_COL_VALUE', 'Value'),
  ('ADMIN_DENYLIST_COL_REASON', 'Reason'),
  ('ADMIN_BREAK_GLASS_COL_STATUS', 'Status'),
  ('ADMIN_BREAK_GLASS_COL_PERM', 'Permission'),
  ('ADMIN_BREAK_GLASS_COL_REASON', 'Reason'),
  ('ADMIN_BREAK_GLASS_COL_ACTIONS', 'Actions'),
  ('ADMIN_OBS_HEATMAP_COL_COUNTRY', 'Country'),
  ('ADMIN_OBS_HEATMAP_COL_USERS', 'Users'),
  ('ADMIN_ACCESS_REVIEW_COL_EMAIL', 'Email'),
  ('ADMIN_ACCESS_REVIEW_COL_STATUS', 'Status'),
  ('ADMIN_ACCESS_REVIEW_COL_ROLE', 'Role'),
  ('ADMIN_ATTEST_COL_PERIOD', 'Period'),
  ('ADMIN_ATTEST_COL_WHEN', 'When'),
  ('ADMIN_ATTEST_COL_NOTES', 'Notes'),
  ('ADMIN_ENTERPRISE_COL_EMAIL', 'Email'),
  ('ADMIN_ENTERPRISE_COL_COMPANY', 'Company'),
  ('ADMIN_ENTERPRISE_COL_STATUS', 'Status'),
  ('ADMIN_PLAN_COL_NAME', 'Plan'),
  ('ADMIN_PLAN_COL_KIND', 'Kind'),
  ('ADMIN_EMAIL_COL_KIND', 'Kind'),
  ('ADMIN_EMAIL_COL_CODE', 'Code'),
  ('ADMIN_RBAC_COL_NAME', 'Name'),
  ('ADMIN_RBAC_COL_SLUG', 'Slug'),
  ('ADMIN_RBAC_COL_PERMS', 'Permissions'),
  ('ADMIN_RBAC_COL_CODE', 'Code'),
  ('ADMIN_RBAC_COL_DESC', 'Description'),
  ('ADMIN_RBAC_COL_EMAIL', 'Email'),
  ('ADMIN_RBAC_COL_ROLE', 'Role'),
  ('ADMIN_RBAC_COL_STATUS', 'Status'),
  ('ADMIN_AUTH_COL_SCOPE', 'Scope'),
  ('ADMIN_AUTH_COL_VALUE', 'Value'),
  ('ADMIN_LEGAL_COL_ID', 'Section'),
  ('ADMIN_LEGAL_COL_STATUS', 'Status'),
  ('ADMIN_USER_COL_PROVIDER', 'Provider'),
  ('ADMIN_USER_COL_IDENTITY', 'Identity'),
  ('ADMIN_USER_COL_WORKSPACE', 'Workspace'),
  ('ADMIN_USER_COL_ROLE', 'Role'),
  ('ADMIN_USER_COL_DEVICE', 'Device'),
  ('ADMIN_USER_COL_JA4', 'JA4'),
  ('ADMIN_USER_COL_LINKED', 'Linked account'),
  ('ADMIN_CREDIT_COL_AMOUNT', 'Credits'),
  ('ADMIN_CREDIT_COL_REASON', 'Reason'),
  ('ADMIN_CREDIT_COL_WHEN', 'When'),
  ('ADMIN_TOPUP_COL_AMOUNT', 'Amount'),
  ('ADMIN_TOPUP_COL_SOURCE', 'Source'),
  ('ADMIN_TOPUP_COL_WHEN', 'When')
on conflict (code) do nothing;
