package authsettings

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/usetrim/trim/server/internal/subscriptions"
	"github.com/usetrim/trim/server/pkg/localchrome"
)

// SyncAllowedProviders upserts public.auth_settings from ALLOWED_AUTH_PROVIDERS.
// Keeps the signup trigger allow-list aligned with the API env (no drift).
func SyncAllowedProviders(ctx context.Context, db *pgxpool.Pool, providers []string) error {
	if db == nil {
		return fmt.Errorf("database required")
	}
	clean := make([]string, 0, len(providers))
	seen := map[string]struct{}{}
	for _, p := range providers {
		p = strings.ToLower(strings.TrimSpace(p))
		if p == "" {
			continue
		}
		if _, ok := seen[p]; ok {
			continue
		}
		seen[p] = struct{}{}
		clean = append(clean, p)
	}
	if len(clean) == 0 {
		return fmt.Errorf("no providers to sync")
	}

	_, err := db.Exec(ctx, `
		insert into public.auth_settings (id, allowed_providers, updated_at)
		values ('default', $1::text[], now())
		on conflict (id) do update set
			allowed_providers = excluded.allowed_providers,
			updated_at = now()
	`, clean)
	if err != nil {
		return fmt.Errorf("auth_settings upsert: %w", err)
	}
	return nil
}

// ListAllowedProviders reads the live allow-list from auth_settings (source of truth).
func ListAllowedProviders(ctx context.Context, db *pgxpool.Pool) ([]string, error) {
	if db == nil {
		return nil, fmt.Errorf("database required")
	}
	var providers []string
	err := db.QueryRow(ctx, `
		select coalesce(allowed_providers, '{}'::text[])
		from public.auth_settings
		where id = 'default'
	`).Scan(&providers)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(providers))
	for _, p := range providers {
		p = strings.ToLower(strings.TrimSpace(p))
		if p == "" {
			continue
		}
		out = append(out, p)
	}
	return out, nil
}

type providerItem struct {
	ID           string `json:"id"`
	DisplayName  string `json:"display_name"`
	ActionLabel  string `json:"action_label"`
	PendingLabel string `json:"pending_label"`
}

// PublicProvidersHandler returns GET /api/v1/public/auth-providers from the database.
// supportEmail is COMPANY_SUPPORT_EMAIL (empty fails closed in legal contact sections).
func PublicProvidersHandler(db *pgxpool.Pool, supportEmail string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		dbMsg := func(codes ...string) func(string) string {
			m := subscriptions.LoadSiteMessages(r.Context(), db, codes)
			return func(code string) string { return subscriptions.SiteMsg(m, code) }
		}
		providers, err := ListAllowedProviders(r.Context(), db)
		if err != nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": dbMsg("AUTH_PROVIDERS_UNAVAILABLE")("AUTH_PROVIDERS_UNAVAILABLE"),
			})
			return
		}
		privacySections, err := subscriptions.LegalPrivacySections(r.Context(), db, supportEmail)
		if err != nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": dbMsg("LEGAL_PRIVACY_UNAVAILABLE")("LEGAL_PRIVACY_UNAVAILABLE"),
			})
			return
		}
		termsSections, err := subscriptions.LegalTermsSections(r.Context(), db, supportEmail)
		if err != nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": dbMsg("LEGAL_TERMS_UNAVAILABLE")("LEGAL_TERMS_UNAVAILABLE"),
			})
			return
		}
		var defaultPageSize int
		_ = db.QueryRow(r.Context(), `
			select coalesce(default_page_size, 0) from public.billing_settings where id = 'default'
		`).Scan(&defaultPageSize)
		if defaultPageSize < 1 {
			defaultPageSize = 0
		}
		// Skeleton card counts for the plan modal: same visibility filters the
		// plans UI uses (subscription/enterprise vs topup), so shimmer matches.
		var planCardCount, planSubscriptionCardCount, planTopupCardCount int
		_ = db.QueryRow(r.Context(), `
			select count(*) from public.plan_catalog where is_public = true and is_active = true
		`).Scan(&planCardCount)
		_ = db.QueryRow(r.Context(), `
			select count(*) from public.plan_catalog
			where is_public = true and is_active = true and plan_kind <> 'topup'
		`).Scan(&planSubscriptionCardCount)
		_ = db.QueryRow(r.Context(), `
			select count(*) from public.plan_catalog
			where is_public = true and is_active = true and plan_kind = 'topup'
		`).Scan(&planTopupCardCount)
		if planCardCount < 0 {
			planCardCount = 0
		}
		if planSubscriptionCardCount < 0 {
			planSubscriptionCardCount = 0
		}
		if planTopupCardCount < 0 {
			planTopupCardCount = 0
		}
		siteCodes := []string{
			"LANDING_BRAND", "LANDING_NAV_DASHBOARD", "LANDING_NAV_SIGN_IN", "LANDING_NAV_PRICING",
			"LANDING_EYEBROW", "LANDING_HEADLINE", "LANDING_TAGLINE",
			"LANDING_CTA_START", "LANDING_CTA_SOURCE",
			"LANDING_FOOTER_PRIVACY", "LANDING_FOOTER_TERMS", "LANDING_FOOTER_GITHUB",
			"LANDING_COPYRIGHT_FMT", "LANDING_SOURCE_URL", "LANDING_INSTALL_SNIPPET",
			"LANDING_DEMO_TITLE", "LANDING_DEMO_SUBTITLE",
			"LANDING_DEMO_BEFORE_LABEL", "LANDING_DEMO_AFTER_LABEL",
			"LANDING_DEMO_RUN_LABEL", "LANDING_DEMO_REPLAY_LABEL",
			"LANDING_DEMO_TOKENS_IN_FMT", "LANDING_DEMO_TOKENS_OUT_FMT", "LANDING_DEMO_SAVED_FMT",
			"LANDING_DEMO_BEFORE_BODY", "LANDING_DEMO_AFTER_BODY",
			"LANDING_HOW_TITLE",
			"LANDING_HOW_1_TITLE", "LANDING_HOW_1_BODY",
			"LANDING_HOW_2_TITLE", "LANDING_HOW_2_BODY",
			"LANDING_HOW_3_TITLE", "LANDING_HOW_3_BODY",
			"LANDING_PRICING_TITLE", "LANDING_PRICING_SUBTITLE", "LANDING_PRICING_CTA",
			"LANDING_PRICING_ANNUAL", "LANDING_PRICING_MONTHLY",
			"LANDING_PRICING_POPULAR_BADGE",
			"LANDING_PRICING_ANNUAL_BILLING", "LANDING_PRICING_ANNUAL_SAVE_HINT_FMT",
			"LANDING_INSTALL_TITLE", "LANDING_CTA_DEMO", "LANDING_HERO_NOTE",
			"LANDING_NAV_WHY", "LANDING_NAV_HOW", "LANDING_NAV_INSTALL",
			"LANDING_STATS_TITLE", "LANDING_STATS_SUBTITLE",
			"LANDING_STAT_1_VALUE", "LANDING_STAT_1_LABEL",
			"LANDING_STAT_2_VALUE", "LANDING_STAT_2_LABEL",
			"LANDING_STAT_3_VALUE", "LANDING_STAT_3_LABEL", "LANDING_STAT_3_HINT",
			"LANDING_FLOW_TITLE", "LANDING_FLOW_SUBTITLE",
			"LANDING_FLOW_1_TITLE", "LANDING_FLOW_1_BODY",
			"LANDING_FLOW_2_TITLE", "LANDING_FLOW_2_BODY",
			"LANDING_FLOW_3_TITLE", "LANDING_FLOW_3_BODY",
			"LANDING_FLOW_4_TITLE", "LANDING_FLOW_4_BODY",
			"LANDING_WHY_TITLE", "LANDING_WHY_SUBTITLE",
			"LANDING_WHY_1_TITLE", "LANDING_WHY_1_BODY",
			"LANDING_WHY_2_TITLE", "LANDING_WHY_2_BODY",
			"LANDING_WHY_3_TITLE", "LANDING_WHY_3_BODY",
			"LANDING_WHY_4_TITLE", "LANDING_WHY_4_BODY",
			"LANDING_WHY_5_TITLE", "LANDING_WHY_5_BODY",
			"LANDING_WHY_6_TITLE", "LANDING_WHY_6_BODY",
			"LANDING_WHY_7_TITLE", "LANDING_WHY_7_BODY",
			"LANDING_WHY_8_TITLE", "LANDING_WHY_8_BODY",
			"LANDING_WHY_9_TITLE", "LANDING_WHY_9_BODY",
			"LANDING_WHY_10_TITLE", "LANDING_WHY_10_BODY",
			"LANDING_WHY_11_TITLE", "LANDING_WHY_11_BODY",
			"LANDING_WHY_12_TITLE", "LANDING_WHY_12_BODY",
			"LANDING_USE_TITLE", "LANDING_USE_SUBTITLE",
			"LANDING_USE_1_TITLE", "LANDING_USE_1_BODY",
			"LANDING_USE_2_TITLE", "LANDING_USE_2_BODY",
			"LANDING_USE_3_TITLE", "LANDING_USE_3_BODY",
			"LANDING_INSTALL_SUBTITLE", "LANDING_DEMO_COST_HINT",
			"LEGAL_PRIVACY_TITLE", "LEGAL_TERMS_TITLE", "LEGAL_UPDATED_PREFIX", "LEGAL_UPDATED_DATE",
			"LEGAL_LINK_PRIVACY", "LEGAL_LINK_TERMS", "LEGAL_LINK_HOME",
			"SITE_HTML_LANG",
			"DASHBOARD_META_SEP", "CLI_LOGIN_PHRASE_OR", "CLI_LOGIN_PHRASE_COMMA",
			"AUTH_PROVIDERS_EMPTY", "LOGIN_TITLE", "LOGIN_PROVIDER_DISABLED", "LOGIN_FAILED",
			"LOGIN_DEFAULT_NEXT", "LOGIN_DEFAULT_NEXT_MISSING",
			"ADMIN_LOGIN_TITLE", "ADMIN_LOGIN_DEFAULT_NEXT", "ADMIN_LOGIN_DEFAULT_NEXT_MISSING",
			"LOGIN_ENV_APP_URL_MISSING", "LOGIN_OAUTH_EXCHANGE_FAILED", "LOGIN_MISSING_SUPABASE_ENV",
			"LOGIN_OAUTH_EMAIL_MISSING",
			"LOGIN_OAUTH_LINK_FAILED",
			"AUTH_OAUTH_LINK_INTENT",
			"AUTH_PROVIDERS_UNAVAILABLE",
			"APP_PATH_DASHBOARD", "APP_PATH_TEAM", "APP_PATH_SETTINGS",
			"APP_PATH_TRACES", "APP_PATH_RECEIPTS", "APP_PATH_ENTERPRISE",
			"APP_PATH_RECEIPTS_PREFIX", "APP_PATH_LOGIN",
			"APP_PATH_PRIVACY", "APP_PATH_TERMS", "APP_PATH_HOME", "APP_PATH_UPGRADE",
			"APP_PATH_AUTH_CALLBACK", "APP_PATH_CLI_AUTH", "APP_PATH_INVITE_PREFIX",
			"DASHBOARD_NAV_TRACES", "DASHBOARD_NAV_RECEIPTS", "DASHBOARD_NAV_ENTERPRISE",
			"AUTH_NOT_SIGNED_IN", "DIALOG_CLOSE", "DIALOG_CANCEL",
			"AUTH_GOOGLE_OAUTH_ACCESS_TYPE", "AUTH_GOOGLE_OAUTH_PROMPT",
			"AUTH_GOOGLE_OAUTH_PARAMS_MISSING",
			"AUTH_GITHUB_OAUTH_SCOPES", "AUTH_GITHUB_OAUTH_SCOPES_MISSING",
			"AUTH_GITLAB_OAUTH_SCOPES", "AUTH_GITLAB_OAUTH_SCOPES_MISSING",
			"DASHBOARD_METRIC_PLAN", "DASHBOARD_METRIC_CREDITS", "DASHBOARD_METRIC_REMAINING",
			"DASHBOARD_METRIC_TOKENS_SAVED", "DASHBOARD_METRIC_TAB",
			"DASHBOARD_METRIC_LINES_ADDED", "DASHBOARD_METRIC_LINES_DELETED",
			"DASHBOARD_CHART_TOKEN_SERIES", "DASHBOARD_CHART_MODELS",
			"DASHBOARD_CHART_OUTCOMES", "DASHBOARD_CHART_MODES", "DASHBOARD_PAGE_EYEBROW",
			"DASHBOARD_TRACES_TITLE", "DASHBOARD_RECEIPTS_TITLE",
			"EVENTS_COL_WHEN", "EVENTS_COL_MODEL", "EVENTS_COL_MODE",
			"EVENTS_COL_TOKENS", "EVENTS_COL_LATENCY", "EVENTS_COL_VIEW",
			"EVENTS_DATE_RANGE_PLACEHOLDER", "EVENTS_DATE_RANGE_DESC",
			"EVENTS_SEARCH", "EVENTS_SEARCH_DESC",
			"RECEIPTS_COL_DATE", "RECEIPTS_COL_INVOICE",
			"RECEIPTS_COL_STATUS", "RECEIPTS_COL_TOTAL", "RECEIPTS_COL_VIEW",
			"RECEIPTS_SEARCH", "RECEIPTS_SEARCH_DESC", "ACTION:RECEIPTS_SYNC",
			"ENTERPRISE_ME_TITLE", "ENTERPRISE_ME_COL_COMPANY", "ENTERPRISE_ME_COL_STATUS",
			"ENTERPRISE_ME_COL_REQUESTED", "ENTERPRISE_ME_COL_OFFERED", "ENTERPRISE_ME_COL_CREATED",
			"WORKSPACE_LIST_TITLE", "WORKSPACE_MEMBERS_TITLE", "WORKSPACE_INVITES_TITLE",
			"RECEIPT_COL_DESCRIPTION", "RECEIPT_COL_SKU", "RECEIPT_COL_QTY",
			"RECEIPT_COL_UNIT", "RECEIPT_COL_AMOUNT",
			"RECEIPT_SECTION_BILL_TO", "RECEIPT_SECTION_PERIOD", "RECEIPT_SECTION_AMOUNT",
			"RECEIPT_SECTION_STATUS", "RECEIPT_SECTION_PAYMENT",
			"RECEIPT_FOOTER",
			"PREFERENCES_PAGE_TITLE", "PREFERENCES_PAGE_DESCRIPTION", "PREFERENCES_TIER_TITLE",
			"PREFERENCES_DEEP_LABEL", "PREFERENCES_CLI_TITLE", "PREFERENCES_KEYS_TITLE",
			"PREFERENCES_BACK_LABEL", "PREFERENCES_ACCOUNT_TITLE", "PREFERENCES_AUTH_PROVIDER_PREFIX",
			"PREFERENCES_LINK_HINT", "PREFERENCES_UNLINK_CONFIRM", "PREFERENCES_UNLINK_LAST_BLOCKED",
			"TABLE_ROW_ACTIONS",
			"ACTION:PREFERENCES_SAVE", "PENDING:PREFERENCES_SAVE",
			"ACTION:AUTH_UNLINK", "PENDING:AUTH_UNLINK",
			"ACTION:SIGN_OUT", "PENDING:SIGN_OUT",
			"SEO_TITLE_TEMPLATE", "SEO_DEFAULT_TITLE", "SEO_DEFAULT_DESCRIPTION",
			"SEO_OG_SITE_NAME", "SEO_OG_TYPE", "SEO_TWITTER_CARD",
			"SEO_ROBOTS_INDEX", "SEO_ROBOTS_NOINDEX",
			"PAGE_404_CODE", "PAGE_404_TITLE", "PAGE_404_HEADING", "PAGE_404_BODY",
			"PAGE_404_HOME_CTA", "PAGE_404_DOCS_CTA", "PAGE_404_DOCS_HREF",
			"PAGE_ERROR_TITLE", "PAGE_ERROR_HEADING", "PAGE_ERROR_BODY",
			"PAGE_ERROR_RETRY_CTA", "PAGE_ERROR_HOME_CTA",
			"ADMIN_PAGE_404_TITLE", "ADMIN_PAGE_404_HEADING", "ADMIN_PAGE_404_BODY", "ADMIN_PAGE_404_HOME_CTA",
			"ADMIN_PAGE_ERROR_TITLE", "ADMIN_PAGE_ERROR_HEADING", "ADMIN_PAGE_ERROR_BODY",
			"ADMIN_PAGE_ERROR_RETRY_CTA", "ADMIN_PAGE_ERROR_HOME_CTA",
			"ADMIN_SEO_DEFAULT_TITLE", "ADMIN_SEO_DEFAULT_DESCRIPTION", "ADMIN_SEO_ROBOTS",
			"LANDING_NAV_CONTACT", "APP_PATH_CONTACT",
			"CONTACT_PAGE_TITLE", "CONTACT_PAGE_HEADING", "CONTACT_PAGE_BODY", "CONTACT_META_DESCRIPTION",
			"CONTACT_EMAIL_LABEL", "CONTACT_OPEN_MAIL_CTA", "CONTACT_TOPICS_HEADING",
			"CONTACT_TOPIC_GENERAL_LABEL", "CONTACT_TOPIC_GENERAL_DESC",
			"CONTACT_TOPIC_GENERAL_SUBJECT", "CONTACT_TOPIC_GENERAL_BODY",
			"CONTACT_TOPIC_BILLING_LABEL", "CONTACT_TOPIC_BILLING_DESC",
			"CONTACT_TOPIC_BILLING_SUBJECT", "CONTACT_TOPIC_BILLING_BODY",
			"CONTACT_TOPIC_SALES_LABEL", "CONTACT_TOPIC_SALES_DESC",
			"CONTACT_TOPIC_SALES_SUBJECT", "CONTACT_TOPIC_SALES_BODY",
			"CONTACT_TOPIC_SECURITY_LABEL", "CONTACT_TOPIC_SECURITY_DESC",
			"CONTACT_TOPIC_SECURITY_SUBJECT", "CONTACT_TOPIC_SECURITY_BODY",
			"DEFAULT_AUTO_START_WITH_IDE",
			"CLI_AUTOSTART_ENABLED", "CLI_AUTOSTART_DISABLED", "CLI_AUTOSTART_UNSET",
			"CLI_AUTOSTART_ENABLE_HINT", "CLI_AUTOSTART_DISABLE_HINT",
			"CLI_AUTOSTART_ENABLED_OK", "CLI_AUTOSTART_DISABLED_OK", "CLI_AUTOSTART_DAEMON_HINT",
			"CLI_AUTOSTART_DAEMON_SKIPPED_OFF", "CLI_AUTOSTART_DAEMON_SKIPPED_UNSET",
			"CLI_AUTOSTART_SKIPPED_MANAGED", "CLI_AUTOSTART_SKIPPED_DNT",
			"CLI_AUTOSTART_MANAGED_OFF_HINT", "CLI_AUTOSTART_SYNC_DAEMON_OK",
			"CLI_AUTOSTART_PREF_POLL_MS", "CLI_AUTOSTART_ENFORCER_STOPPED",
			"AUTOSTART_PREF_POLL_MIN_MS", "AUTOSTART_PREF_POLL_MAX_MS",
			"AUTOSTART_TIMEOUT_MIN_MS", "AUTOSTART_TIMEOUT_MAX_MS",
			"CLI_DAEMON_RESTART_SEC", "CLI_STOP_ON_DISABLE_OK",
			"DAEMON_RESTART_MIN_SEC", "DAEMON_RESTART_MAX_SEC",
			"IDE_PROXY_HEALTH_URL", "IDE_PROXY_SHUTDOWN_URL",
			"CLI_PROXY_HEALTH_TIMEOUT_MS", "CLI_PROXY_SHUTDOWN_TIMEOUT_MS", "CLI_HTTP_SHUTDOWN_TIMEOUT_MS",
			"CLI_PROXY_FALLBACK_UNCOMPRESSED",
			"PROXY_ACTIVE_FILE_PROTECTION",
			"CLI_STOP_OK", "CLI_STOP_FAILED_FMT", "CLI_STOP_URL_MISSING",
			"CLI_CONFIG_GET_AUTOSTART_UNSET", "CLI_CONFIG_GET_AUTOSTART_FMT",
			"CLI_HELP_AUTOSTART_SHORT", "CLI_HELP_AUTOSTART_STATUS_SHORT",
			"CLI_HELP_AUTOSTART_ENABLE_SHORT", "CLI_HELP_AUTOSTART_DISABLE_SHORT",
			"ADMIN_FORBIDDEN_PAGE", "ADMIN_BOOTSTRAP_REQUIRED", "DIALOG_CANCEL",
		}
		cliChromeCodes := []string{
			"ACTION:API_KEY_ISSUE",
			"PENDING:API_KEY_ISSUE",
			"ACTION:API_KEY_ISSUE_RETRY",
			"ACTION:API_KEY_ISSUE_ANOTHER",
			"ACTION:API_KEY_COPY",
			"PENDING:API_KEY_COPY",
			"ACTION:API_KEY_COPIED",
			"CLI_AUTH_EYEBROW",
			"CLI_AUTH_TITLE",
			"CLI_AUTH_BODY",
			"CLI_AUTH_ISSUE_FAILED",
			"CLI_AUTH_FOOTER",
			"CLI_AUTH_COPIED_RESET_MS",
			"CLI_LOGIN_SIGN_IN_FMT",
			"CLI_LOGIN_OPENING_BROWSER",
			"CLI_LOGIN_PASTE_KEY",
			"CLI_LOGIN_KEY_REQUIRED",
			"CLI_LOGIN_SUCCESS",
			"CLI_LOGOUT_SUCCESS",
			"CLI_LOGOUT_ALREADY",
			"CLI_CHROME_UNAVAILABLE",
			"CLI_BROWSER_UNSUPPORTED_FMT",
			"CLI_STATUS_NOT_LOGGED_IN",
			"CLI_QUOTA_EXHAUSTED_TITLE",
			"CLI_QUOTA_EXHAUSTED_BODY",
			"CLI_QUOTA_UPGRADE_HINT_FMT",
			"CLI_QUOTA_UPGRADE_OPENING",
			"CLI_QUOTA_UPGRADE_URL_MISSING",
			"CLI_HELP_UPGRADE_SHORT",
			"CLI_LOGIN_PHRASE_OR",
			"CLI_LOGIN_PHRASE_COMMA",
			"CLI_LOGIN_PHRASE_COMMA_OR",
			"CLI_SETUP_ENDPOINT_FMT",
			"CLI_SETUP_NONE_FOUND",
			"CLI_SETUP_UPDATED_HEADER",
			"CLI_SETUP_SHELL_HEADER",
			"CLI_SETUP_JETBRAINS_HINT",
			"CLI_SETUP_API_ENDPOINT_FMT",
			"CLI_SETUP_NEXT_HEADER",
			"CLI_SETUP_STEP_START",
			"CLI_SETUP_STEP_RESTART",
			"CLI_SETUP_STEP_LOGIN",
			"CLI_SETUP_STEP_DASHBOARD_FMT",
			"CLI_SETUP_OPTIONAL_TLS",
			"CLI_SETUP_TLS_THEN",
			"CLI_SETUP_TLS_GENERATED_FMT",
			"CLI_SETUP_TLS_CERT_FMT",
			"CLI_SETUP_TLS_KEY_FMT",
			"CLI_SETUP_TLS_KEY_PATH_FMT",
			"CLI_SETUP_SHELL_OPENAI_FMT",
			"CLI_SETUP_SHELL_ANTHROPIC_FMT",
			"CLI_SETUP_TLS_START",
			"CLI_SETUP_TLS_POINT_IDE",
			"CLI_SETUP_TLS_ENV_REQUIRED",
			"CLI_SETUP_TLS_DAYS_INVALID",
			"CLI_POW_CLIENT_REQUIRED",
			"CLI_POW_428_MISSING",
			"CLI_POW_SOLVE_FAILED",
			"CLI_POW_PARSE_FAILED_FMT",
			"CLI_SETUP_WROTE_FMT",
			"CLI_SETUP_PRODUCT_CURSOR",
			"CLI_SETUP_PRODUCT_VSCODE",
			"CLI_SETUP_PRODUCT_WINDSURF",
			"CLI_SETUP_PRODUCT_CONTINUE",
			"CLI_SETUP_PRODUCT_ZED",
			"CLI_SETUP_PRODUCT_JETBRAINS",
			"CLI_SETUP_CONTINUE_NO_MODEL",
			"CLI_START_RUNNING_FMT",
			"CLI_START_DASHBOARD_FMT",
			"CLI_START_MODE_FMT",
			"CLI_START_POINT_IDE_FMT",
			"CLI_START_RULES_FMT",
			"CLI_START_STOPPED",
			"CLI_ERR_FMT",
			"CLI_PROXY_FAILED_FMT",
			"CLI_MAIN_ERR_FMT",
			"CLI_DAEMON_UNSUPPORTED_FMT",
			"CLI_DAEMON_LAUNCHD_INSTALLED_FMT",
			"CLI_DAEMON_LAUNCHD_MISSING",
			"CLI_DAEMON_SYSTEMD_INSTALLED_FMT",
			"CLI_DAEMON_SYSTEMD_MISSING",
			"CLI_DAEMON_WINDOWS_MISSING",
			"CLI_DAEMON_LAUNCHD_OK_FMT",
			"CLI_DAEMON_LAUNCHD_HINT",
			"CLI_DAEMON_LAUNCHD_REMOVED",
			"CLI_DAEMON_SYSTEMD_OK_FMT",
			"CLI_DAEMON_SYSTEMD_REMOVED",
			"CLI_DAEMON_WINDOWS_OK",
			"CLI_DAEMON_WINDOWS_REMOVED",
			"CLI_TELEMETRY_ENABLED",
			"CLI_TELEMETRY_DISABLE_HINT",
			"CLI_TELEMETRY_ENV_HINT",
			"CLI_TELEMETRY_DISABLED",
			"CLI_TELEMETRY_ENABLE_HINT",
			"CLI_TELEMETRY_DISABLED_OK",
			"CLI_TELEMETRY_ENABLED_OK",
			"CLI_COMPRESS_FILE_REQUIRED",
			"CLI_COMPRESS_MODE_REQUIRED",
			"CLI_COMPRESS_MODE_INVALID",
			"CLI_TREESITTER_REQUIRED",
			"CLI_COMPRESS_DEEP_PREFS_REQUIRED",
			"CLI_COMPRESS_DEEP_RESULT_FMT",
			"CLI_COMPRESS_WROTE_FMT",
			"CLI_STATS_LIVE_HEADER",
			"CLI_STATS_LIVE_OFFLINE_FMT",
			"CLI_STATS_URL_FMT",
			"CLI_STATS_URL_MISSING",
			"CLI_STATS_SQLITE_TODAY_FMT",
			"CLI_STATS_SQLITE_SERIES_HEADER",
			"CLI_STATS_SQLITE_SERIES_ROW_FMT",
			"CLI_STATS_TUI_TIP",
			"CLI_STATS_DEEP_STATUS_FMT",
			"CLI_STATS_DEEP_STAGE_FMT",
			"CLI_STATS_LAST_REQUEST_FMT",
			"CLI_STATS_DOOR_FMT",
			"CLI_STATS_DASHBOARD_TIP_FMT",
			"CLI_HELP_STATUS_LONG",
			"CLI_STATUS_API_FMT",
			"CLI_DEEP_BOOTSTRAP_REQS",
			"CLI_DEEP_BOOTSTRAP_PIP",
			"CLI_DEEP_REQUIREMENTS_MISSING",
			"CLI_DEEP_AUTO_INSTALL",
			"CLI_DEEP_BIN_ENV_MISSING_FMT",
			"CLI_DEEP_BIN_MISSING",
			"CLI_DEEP_PY_ENV_MISSING_FMT",
			"CLI_DEEP_PY_MISSING",
			"CLI_DEEP_LLM_MISSING_FMT",
			"CLI_DEEP_PIP_FAILED",
			"CLI_DEEP_TARGET_REQUIRED",
			"CLI_DEEP_ENGINE_REQUIRED",
			"CLI_DEEP_QUESTION_REQUIRED",
			"CLI_DEEP_OPTIMIZE_FMT",
			"CLI_DEEP_TIMEOUT",
			"CLI_DEEP_PARSE_FMT",
			"CLI_PROXY_DEEP_FAILED_FMT",
			"CLI_PROXY_LIVE_DEEP_MODE_FMT",
			"CLI_PROXY_LIVE_DEEP_ENABLED_FMT",
			"CLI_PROXY_DEEP_COMPACT_STUB",
			"CLI_PROXY_DEEP_CHROME_REQUIRED",
			"CLI_PROXY_DEEP_PREFS_REQUIRED",
			"CLI_PROXY_DEEP_SKIPPED_MIN_FMT",
			"CLI_PROXY_DEEP_SKIPPED_STREAM",
			"CLI_PROXY_DEEP_OOM_SKIPPED",
			"CLI_PROXY_DEEP_RUNTIME_REQUIRED",
			"CLI_PROXY_ADAPTER_REQUIRED",
			"CLI_PROXY_ADAPTER_UNKNOWN_DIALECT_FMT",
			"CLI_PROXY_ADAPTER_MODEL_REQUIRED",
			"CLI_PROXY_ADAPTER_ALIAS_REQUIRED_FMT",
			"CLI_PROXY_ADAPTER_TRANSLATE_FMT",
			"CLI_PROXY_ADAPTER_AUTH_FMT",
			"CLI_PROXY_ADAPTER_RESPONSE_FMT",
			"CLI_PROXY_ADAPTER_ENABLED_FMT",
			"CLI_PROXY_MODELS_NOT_SYNCED",
			"CLI_PROXY_MODELS_METHOD",
			"CLI_PROXY_ERR_BASE_URL_DOUBLE_V1",
			"CLI_PROXY_ERR_MODEL_NOT_FOUND_FMT",
			"CLI_PROXY_ERR_UNKNOWN_MODEL_FMT",
			"CLI_PROXY_ERR_UPSTREAM_AUTH_FMT",
			"CLI_PROXY_ERR_UPSTREAM_QUOTA_FMT",
			"CLI_PROXY_ERR_UPSTREAM_UNAVAILABLE_FMT",
			"CLI_SETUP_CLAUDE_CODE_BLOCK_FMT",
			"CLI_SETUP_CONTINUE_BLOCK_FMT",
			"CLI_SETUP_VSCODE_CHAT_BLOCK_FMT",
			"CLI_PROXY_MODELS_UPSTREAM_NOT_FOUND_FMT",
			"CLI_PROXY_MODELS_UPSTREAM_AUTH",
			"CLI_PROXY_MODELS_UPSTREAM_UNSUPPORTED_FMT",
			"CLI_PROXY_MODELS_UPSTREAM_ADAPTER_REQUIRED",
			"CLI_PROXY_DOOR_OPENAI",
			"CLI_PROXY_DOOR_ANTHROPIC",
			"CLI_PREFS_ENGINE_INVALID",
			"CLI_PREFS_TARGET_NONNEG",
			"CLI_PREFS_TIER_REQUIRED",
			"CLI_PREFS_ENGINE_REQUIRED",
			"CLI_PREFS_TARGET_REQUIRED",
			"CLI_CONFIG_GET_TIER_FMT",
			"CLI_CONFIG_GET_ENGINE_FMT",
			"CLI_CONFIG_GET_TARGET_FMT",
			"CLI_CONFIG_UNKNOWN_KEY_FMT",
			"CLI_CONFIG_TARGET_POSITIVE",
			"CLI_CONFIG_SAVED_FMT",
			"CLI_CONFIG_NOT_LOGGED_IN",
			"CLI_CONFIG_SYNC_FAILED_FMT",
			"CLI_CONFIG_SYNCED_FMT",
			"CLI_HELP_ROOT_SHORT",
			"CLI_HELP_ROOT_LONG",
			"CLI_HELP_GROUP_EVERYDAY",
			"CLI_HELP_GROUP_ADVANCED",
			"CLI_HELP_START_SHORT",
			"CLI_HELP_START_LONG",
			"CLI_HELP_START_FLAG_PORT",
			"CLI_HELP_LOGIN_SHORT",
			"CLI_HELP_LOGOUT_SHORT",
			"CLI_HELP_UNINSTALL_SHORT",
			"CLI_HELP_UNINSTALL_LONG",
			"CLI_HELP_UNINSTALL_FLAG_KEEP_DATA",
			"CLI_UNINSTALL_STARTING",
			"CLI_UNINSTALL_STOPPED",
			"CLI_UNINSTALL_DAEMON_OK",
			"CLI_UNINSTALL_LOGOUT_OK",
			"CLI_UNINSTALL_SETUP_REVERTED_FMT",
			"CLI_UNINSTALL_SETUP_NONE",
			"CLI_UNINSTALL_CONFIG_REMOVED_FMT",
			"CLI_UNINSTALL_LOGS_REMOVED",
			"CLI_UNINSTALL_DEEP_OK",
			"CLI_UNINSTALL_DEEP_SKIPPED",
			"CLI_UNINSTALL_SIDECAR_REMOVED_FMT",
			"CLI_UNINSTALL_BINARY_REMOVED_FMT",
			"CLI_UNINSTALL_BINARY_MANUAL_FMT",
			"CLI_UNINSTALL_PATH_REMOVED",
			"CLI_UNINSTALL_DONE",
			"CLI_UNINSTALL_NEXT_EXT",
			"CLI_UNINSTALL_NEXT_PKG_BREW",
			"CLI_UNINSTALL_NEXT_PKG_SCOOP",
			"CLI_UNINSTALL_NEXT_PKG_WINGET",
			"CLI_UNINSTALL_HF_HUB_DIRS",
			"CLI_UNINSTALL_HF_CACHE_REL",
			"CLI_UNINSTALL_HF_HUB_SUBDIR",
			"CLI_UNINSTALL_HOME_DIRS_REL",
			"CLI_UNINSTALL_HOME_DIRS_MISSING",
			"CLI_UNINSTALL_DARWIN_LOG_RELS",
			"CLI_UNINSTALL_PIP_PACKAGES",
			"CLI_UNINSTALL_PIP_BINS",
			"CLI_UNINSTALL_PYTHON_BINS",
			"CLI_UNINSTALL_PIP_MODULE",
			"CLI_UNINSTALL_SIDECAR_NAMES",
			"CLI_UNINSTALL_ARP_DISPLAY_NAME",
			"CLI_UNINSTALL_ARP_PUBLISHER",
			"CLI_UNINSTALL_ARP_REG_KEY",
			"CLI_UNINSTALL_ARP_REMOVED",
			"CLI_HELP_STATUS_SHORT",
			"CLI_HELP_STATUS_LONG",
			"CLI_HELP_UPGRADE_SHORT",
			"CLI_HELP_STATS_SHORT",
			"CLI_HELP_STATS_LONG",
			"CLI_HELP_STATS_FLAG_TUI",
			"CLI_HELP_SETUP_SHORT",
			"CLI_HELP_SETUP_LONG",
			"CLI_HELP_SETUP_FLAG_TLS",
			"CLI_HELP_VERSION_SHORT",
			"CLI_HELP_DAEMON_SHORT",
			"CLI_HELP_DAEMON_INSTALL_SHORT",
			"CLI_HELP_DAEMON_UNINSTALL_SHORT",
			"CLI_HELP_DAEMON_STATUS_SHORT",
			"CLI_HELP_DAEMON_RUN_SHORT",
			"CLI_HELP_DAEMON_SERVICE_DESC",
			"CLI_HELP_TELEMETRY_SHORT",
			"CLI_HELP_TELEMETRY_STATUS_SHORT",
			"CLI_HELP_TELEMETRY_DISABLE_SHORT",
			"CLI_HELP_TELEMETRY_ENABLE_SHORT",
			"CLI_HELP_STOP_SHORT",
			"CLI_HELP_TUI_SHORT",
			"CLI_HELP_TUI_LONG",
			"CLI_HELP_COMPRESS_SHORT",
			"CLI_HELP_COMPRESS_LONG",
			"CLI_HELP_COMPRESS_FLAG_MODE",
			"CLI_HELP_COMPRESS_FLAG_DEEP",
			"CLI_HELP_COMPRESS_FLAG_ENGINE",
			"CLI_HELP_COMPRESS_FLAG_QUESTION",
			"CLI_HELP_COMPRESS_FLAG_TARGET",
			"CLI_HELP_COMPRESS_FLAG_BOOTSTRAP",
			"CLI_HELP_COMPRESS_FLAG_OUT",
			"CLI_HELP_CONFIG_SHORT",
			"CLI_HELP_CONFIG_GET_SHORT",
			"CLI_HELP_CONFIG_SET_SHORT",
			"CLI_HELP_CONFIG_SYNC_SHORT",
			"CLI_AUTOSTART_ENABLED",
			"CLI_AUTOSTART_DISABLED",
			"CLI_AUTOSTART_UNSET",
			"CLI_AUTOSTART_ENABLE_HINT",
			"CLI_AUTOSTART_DISABLE_HINT",
			"CLI_AUTOSTART_ENABLED_OK",
			"CLI_AUTOSTART_DISABLED_OK",
			"CLI_AUTOSTART_DAEMON_HINT",
			"CLI_AUTOSTART_DAEMON_SKIPPED_OFF",
			"CLI_AUTOSTART_DAEMON_SKIPPED_UNSET",
			"CLI_AUTOSTART_SKIPPED_MANAGED",
			"CLI_AUTOSTART_SKIPPED_DNT",
			"CLI_AUTOSTART_MANAGED_OFF_HINT",
			"CLI_AUTOSTART_SYNC_DAEMON_OK",
			"CLI_AUTOSTART_PREF_POLL_MS",
			"CLI_AUTOSTART_ENFORCER_STOPPED",
			"AUTOSTART_PREF_POLL_MIN_MS",
			"AUTOSTART_PREF_POLL_MAX_MS",
			"AUTOSTART_TIMEOUT_MIN_MS",
			"AUTOSTART_TIMEOUT_MAX_MS",
			"DEFAULT_AUTO_START_WITH_IDE",
			"CLI_DAEMON_RESTART_SEC",
			"CLI_STOP_ON_DISABLE_OK",
			"DAEMON_RESTART_MIN_SEC",
			"DAEMON_RESTART_MAX_SEC",
			"IDE_PROXY_HEALTH_URL",
			"IDE_PROXY_SHUTDOWN_URL",
			"CLI_PROXY_HEALTH_TIMEOUT_MS",
			"CLI_PROXY_SHUTDOWN_TIMEOUT_MS",
			"CLI_HTTP_SHUTDOWN_TIMEOUT_MS",
			"CLI_PROXY_FALLBACK_UNCOMPRESSED",
			"PROXY_ACTIVE_FILE_PROTECTION",
			"CLI_STOP_OK",
			"CLI_STOP_FAILED_FMT",
			"CLI_STOP_URL_MISSING",
			"CLI_CONFIG_GET_AUTOSTART_UNSET",
			"CLI_CONFIG_GET_AUTOSTART_FMT",
			"CLI_HELP_AUTOSTART_SHORT",
			"CLI_HELP_AUTOSTART_STATUS_SHORT",
			"CLI_HELP_AUTOSTART_ENABLE_SHORT",
			"CLI_HELP_AUTOSTART_DISABLE_SHORT",
			"LOCAL_DOCUMENT_TITLE",
			"LOCAL_BRAND",
			"LOCAL_LEAD_FMT",
			"LOCAL_LABEL_REQUESTS",
			"LOCAL_LABEL_TOKENS_IN",
			"LOCAL_LABEL_TOKENS_OUT",
			"LOCAL_LABEL_SAVED",
			"LOCAL_LABEL_EST_USD",
			"LOCAL_LABEL_LAST_LATENCY",
			"LOCAL_STATS_LAST_DOOR",
			"LOCAL_TUI_LABEL_LAST_DOOR",
			"LOCAL_LABEL_LAST_REQUEST",
			"LOCAL_LAST_REQUEST_VALUE_FMT",
			"LOCAL_LABEL_LAST_SAVED",
			"LOCAL_LABEL_FALLBACKS",
			"LOCAL_LABEL_DEEP_STATUS",
			"LOCAL_LABEL_DEEP_STAGE",
			"LOCAL_LABEL_DEEP_STAGE_SAVED",
			"LOCAL_DEEP_STATUS_APPLIED",
			"LOCAL_DEEP_STATUS_SKIPPED_MIN",
			"LOCAL_DEEP_STATUS_SKIPPED_STREAM",
			"LOCAL_DEEP_STATUS_SKIPPED_EMPTY",
			"LOCAL_DEEP_STATUS_SKIPPED_OFF",
			"LOCAL_DEEP_STATUS_PATH_SKIP",
			"LOCAL_DEEP_STATUS_FAIL_CLOSED_EXPAND",
			"LOCAL_DEEP_STATUS_FAIL_CLOSED_ERROR",
			"LOCAL_DEEP_STATUS_OOM_SKIP",
			"LOCAL_DEEP_STATUS_REJECTED",
			"LOCAL_DEEP_STATUS_FAST_ONLY",
			"LOCAL_SAVINGS_DETAIL_TITLE",
			"LOCAL_SAVINGS_DETAIL_LEAD",
			"LOCAL_SAVINGS_DETAIL_SHOW",
			"LOCAL_SAVINGS_DETAIL_HIDE",
			"LOCAL_SAVINGS_DETAIL_WIRE_FMT",
			"LOCAL_SAVINGS_DETAIL_STAGE_FMT",
			"LOCAL_SAVINGS_DETAIL_STATUS_FMT",
			"LOCAL_SAVINGS_DETAIL_CHROME_TIP",
			"LOCAL_HEADING_BEFORE",
			"LOCAL_HEADING_AFTER",
			"LOCAL_PLAYGROUND_TITLE",
			"LOCAL_PLAYGROUND_LEAD",
			"LOCAL_LABEL_MODE",
			"LOCAL_MODE_MILD",
			"LOCAL_MODE_BALANCED",
			"LOCAL_MODE_AGGRESSIVE",
			"LOCAL_MODE_CUSTOM",
			"LOCAL_LABEL_USER_PROMPT",
			"LOCAL_USER_PROMPT_PLACEHOLDER",
			"LOCAL_PREVIEW_ACTION",
			"LOCAL_PREVIEW_PENDING",
			"LOCAL_INPUT_PLACEHOLDER",
			"LOCAL_HEADING_PREVIEW_IN",
			"LOCAL_HEADING_PREVIEW_OUT",
			"LOCAL_PREVIEW_IDLE",
			"LOCAL_EMPTY_PREVIEW",
			"LOCAL_NO_REQUEST_YET",
			"LOCAL_SERIES_TITLE",
			"LOCAL_SERIES_LEAD",
			"LOCAL_SERIES_EMPTY",
			"LOCAL_SERIES_UNAVAILABLE_FMT",
			"LOCAL_SERIES_HEADER",
			"LOCAL_SERIES_NO_PROVIDER",
			"LOCAL_PREVIEW_META_FMT",
			"LOCAL_PREVIEW_FAILED_FMT",
			"LOCAL_TUI_TITLE",
			"LOCAL_TUI_LABEL_REQUESTS",
			"LOCAL_TUI_LABEL_TOKENS",
			"LOCAL_TUI_LABEL_REDUCTION",
			"LOCAL_TUI_LABEL_EST_SAVED",
			"LOCAL_TUI_LABEL_LAST_LATENCY",
			"LOCAL_TUI_EST_SAVED_FMT",
			"LOCAL_TUI_LATENCY_FMT",
			"LOCAL_TUI_SERIES_ROW_FMT",
			"LOCAL_TUI_SERIES_EMPTY",
			"LOCAL_TUI_SERIES_TITLE",
			"LOCAL_TUI_PROXY_URL_FMT",
			"LOCAL_TUI_OFFLINE_FMT",
			"LOCAL_TUI_UPDATED_PREFIX",
			"LOCAL_TUI_FOOTER",
			"LOCAL_TUI_HINT",
			"LOCAL_TUI_CLOUD_TITLE",
			"LOCAL_TUI_CLOUD_LABEL_TIER",
			"LOCAL_TUI_CLOUD_LABEL_USED",
			"LOCAL_TUI_CLOUD_LABEL_REMAINING",
			"LOCAL_TUI_CLOUD_LABEL_TOPUP",
			"LOCAL_TUI_CLOUD_SIGNED_OUT",
			"LOCAL_TUI_CLOUD_OFFLINE_FMT",
			"LOCAL_FOOT_JSON",
			"LOCAL_FOOT_SERIES",
			"LOCAL_FOOT_PREVIEW",
			"LOCAL_FOOT_METRICS",
			"LOCAL_FOOT_HEALTH",
			"LOCAL_ERR_SERIES_UNAVAILABLE",
			"LOCAL_ERR_BODY_READ",
			"LOCAL_ERR_UPSTREAM_FMT",
			"LOCAL_ERR_METHOD_POST_ONLY",
			"LOCAL_ERR_INVALID_JSON",
			"LOCAL_HTML_LANG",
			"LOCAL_TUI_HTTP_TIMEOUT_UNSET",
			"LOCAL_PREVIEW_TRUNC_SUFFIX",
			"LOCAL_TUI_TRUNC_SUFFIX",
			"LOCAL_STATS_URL_FMT",
			"AUTH_CREDENTIALS_REVOKED",
		}
		siteCodes = append(siteCodes, cliChromeCodes...)
		for _, p := range providers {
			if code := subscriptions.OAuthActionCode(p); code != "" {
				siteCodes = append(siteCodes, "ACTION:"+code, "PENDING:"+code)
			}
			id := strings.ToLower(strings.TrimSpace(p))
			if id != "" {
				siteCodes = append(siteCodes, "AUTH_PROVIDER_DISPLAY_"+strings.ToUpper(id))
			}
		}
		siteDB := subscriptions.LoadSiteMessages(r.Context(), db, siteCodes)
		msg := func(code string) string { return subscriptions.SiteMsg(siteDB, code) }
		items := make([]providerItem, 0, len(providers))
		oauthChrome := map[string]string{}
		for _, p := range providers {
			code := subscriptions.OAuthActionCode(p)
			if code == "" {
				continue
			}
			id := strings.ToLower(strings.TrimSpace(p))
			display := msg("AUTH_PROVIDER_DISPLAY_" + strings.ToUpper(id))
			items = append(items, providerItem{
				ID:           p,
				DisplayName:  display,
				ActionLabel:  msg("ACTION:" + code),
				PendingLabel: msg("PENDING:" + code),
			})
			upper := strings.ToUpper(id)
			put := func(suffix, msgCode string) {
				if v := strings.TrimSpace(msg(msgCode)); v != "" {
					oauthChrome[id+"_"+suffix] = v
				}
			}
			put("oauth_access_type", "AUTH_"+upper+"_OAUTH_ACCESS_TYPE")
			put("oauth_prompt", "AUTH_"+upper+"_OAUTH_PROMPT")
			put("oauth_params_missing", "AUTH_"+upper+"_OAUTH_PARAMS_MISSING")
			put("oauth_scopes", "AUTH_"+upper+"_OAUTH_SCOPES")
			put("oauth_scopes_missing", "AUTH_"+upper+"_OAUTH_SCOPES_MISSING")
		}
		w.Header().Set("Content-Type", "application/json")
		payload := map[string]any{
			"providers":                        providers,
			"items":                            items,
			"provider_count":                   len(items),
			"providers_empty_message":          msg("AUTH_PROVIDERS_EMPTY"),
			"login_title":                      msg("LOGIN_TITLE"),
			"login_default_next":               msg("LOGIN_DEFAULT_NEXT"),
			"admin_login_title":                msg("ADMIN_LOGIN_TITLE"),
			"admin_login_default_next":         msg("ADMIN_LOGIN_DEFAULT_NEXT"),
			"admin_login_default_next_missing": msg("ADMIN_LOGIN_DEFAULT_NEXT_MISSING"),
			"login_provider_disabled_message":  msg("LOGIN_PROVIDER_DISABLED"),
			"login_failed_message":             msg("LOGIN_FAILED"),
			"login_env_app_url_missing":        msg("LOGIN_ENV_APP_URL_MISSING"),
			"login_oauth_exchange_failed":      msg("LOGIN_OAUTH_EXCHANGE_FAILED"),
			"login_missing_supabase_env":       msg("LOGIN_MISSING_SUPABASE_ENV"),
			"login_default_next_missing":       msg("LOGIN_DEFAULT_NEXT_MISSING"),
			"login_auth_providers_unavailable": msg("AUTH_PROVIDERS_UNAVAILABLE"),
			"login_oauth_email_missing":        msg("LOGIN_OAUTH_EMAIL_MISSING"),
			"login_oauth_email_denied":         msg("LOGIN_OAUTH_EMAIL_DENIED"),
			"login_oauth_link_failed":          msg("LOGIN_OAUTH_LINK_FAILED"),
			"oauth_link_intent":                msg("AUTH_OAUTH_LINK_INTENT"),
			"site": map[string]string{
				"brand":                                  msg("LANDING_BRAND"),
				"html_lang":                              msg("SITE_HTML_LANG"),
				"nav_dashboard":                          msg("LANDING_NAV_DASHBOARD"),
				"nav_dashboard_href":                     msg("APP_PATH_DASHBOARD"),
				"nav_sign_in":                            msg("LANDING_NAV_SIGN_IN"),
				"nav_sign_in_href":                       msg("APP_PATH_LOGIN"),
				"nav_pricing":                            msg("LANDING_NAV_PRICING"),
				"nav_contact":                            msg("LANDING_NAV_CONTACT"),
				"path_login":                             msg("APP_PATH_LOGIN"),
				"path_dashboard":                         msg("APP_PATH_DASHBOARD"),
				"path_team":                              msg("APP_PATH_TEAM"),
				"path_settings":                          msg("APP_PATH_SETTINGS"),
				"path_traces":                            msg("APP_PATH_TRACES"),
				"path_receipts":                          msg("APP_PATH_RECEIPTS"),
				"path_enterprise":                        msg("APP_PATH_ENTERPRISE"),
				"path_receipts_prefix":                   msg("APP_PATH_RECEIPTS_PREFIX"),
				"nav_traces":                             msg("DASHBOARD_NAV_TRACES"),
				"nav_receipts":                           msg("DASHBOARD_NAV_RECEIPTS"),
				"nav_enterprise":                         msg("DASHBOARD_NAV_ENTERPRISE"),
				"nav_team":                               msg("DASHBOARD_NAV_TEAM"),
				"nav_settings":                           msg("DASHBOARD_NAV_SETTINGS"),
				"path_privacy":                           msg("APP_PATH_PRIVACY"),
				"path_terms":                             msg("APP_PATH_TERMS"),
				"path_home":                              msg("APP_PATH_HOME"),
				"path_contact":                           msg("APP_PATH_CONTACT"),
				"path_upgrade":                           msg("APP_PATH_UPGRADE"),
				"path_auth_callback":                     msg("APP_PATH_AUTH_CALLBACK"),
				"path_cli_auth":                          msg("APP_PATH_CLI_AUTH"),
				"path_invite_prefix":                     msg("APP_PATH_INVITE_PREFIX"),
				"eyebrow":                                msg("LANDING_EYEBROW"),
				"headline":                               msg("LANDING_HEADLINE"),
				"tagline":                                msg("LANDING_TAGLINE"),
				"cta_start":                              msg("LANDING_CTA_START"),
				"cta_source":                             msg("LANDING_CTA_SOURCE"),
				"footer_privacy":                         msg("LANDING_FOOTER_PRIVACY"),
				"footer_terms":                           msg("LANDING_FOOTER_TERMS"),
				"footer_github":                          msg("LANDING_FOOTER_GITHUB"),
				"copyright_fmt":                          msg("LANDING_COPYRIGHT_FMT"),
				"source_url":                             msg("LANDING_SOURCE_URL"),
				"install_snippet":                        msg("LANDING_INSTALL_SNIPPET"),
				"demo_title":                             msg("LANDING_DEMO_TITLE"),
				"demo_subtitle":                          msg("LANDING_DEMO_SUBTITLE"),
				"demo_before_label":                      msg("LANDING_DEMO_BEFORE_LABEL"),
				"demo_after_label":                       msg("LANDING_DEMO_AFTER_LABEL"),
				"demo_run_label":                         msg("LANDING_DEMO_RUN_LABEL"),
				"demo_replay_label":                      msg("LANDING_DEMO_REPLAY_LABEL"),
				"demo_tokens_in_fmt":                     msg("LANDING_DEMO_TOKENS_IN_FMT"),
				"demo_tokens_out_fmt":                    msg("LANDING_DEMO_TOKENS_OUT_FMT"),
				"demo_saved_fmt":                         msg("LANDING_DEMO_SAVED_FMT"),
				"demo_before_body":                       msg("LANDING_DEMO_BEFORE_BODY"),
				"demo_after_body":                        msg("LANDING_DEMO_AFTER_BODY"),
				"how_title":                              msg("LANDING_HOW_TITLE"),
				"how_1_title":                            msg("LANDING_HOW_1_TITLE"),
				"how_1_body":                             msg("LANDING_HOW_1_BODY"),
				"how_2_title":                            msg("LANDING_HOW_2_TITLE"),
				"how_2_body":                             msg("LANDING_HOW_2_BODY"),
				"how_3_title":                            msg("LANDING_HOW_3_TITLE"),
				"how_3_body":                             msg("LANDING_HOW_3_BODY"),
				"pricing_title":                          msg("LANDING_PRICING_TITLE"),
				"pricing_subtitle":                       msg("LANDING_PRICING_SUBTITLE"),
				"pricing_cta":                            msg("LANDING_PRICING_CTA"),
				"pricing_annual":                         msg("LANDING_PRICING_ANNUAL"),
				"pricing_monthly":                        msg("LANDING_PRICING_MONTHLY"),
				"pricing_popular_badge":                  msg("LANDING_PRICING_POPULAR_BADGE"),
				"pricing_annual_billing":                 msg("LANDING_PRICING_ANNUAL_BILLING"),
				"pricing_annual_save_hint_fmt":           msg("LANDING_PRICING_ANNUAL_SAVE_HINT_FMT"),
				"install_title":                          msg("LANDING_INSTALL_TITLE"),
				"cta_demo":                               msg("LANDING_CTA_DEMO"),
				"hero_note":                              msg("LANDING_HERO_NOTE"),
				"nav_why":                                msg("LANDING_NAV_WHY"),
				"nav_how":                                msg("LANDING_NAV_HOW"),
				"nav_install":                            msg("LANDING_NAV_INSTALL"),
				"stats_title":                            msg("LANDING_STATS_TITLE"),
				"stats_subtitle":                         msg("LANDING_STATS_SUBTITLE"),
				"stat_1_value":                           msg("LANDING_STAT_1_VALUE"),
				"stat_1_label":                           msg("LANDING_STAT_1_LABEL"),
				"stat_2_value":                           msg("LANDING_STAT_2_VALUE"),
				"stat_2_label":                           msg("LANDING_STAT_2_LABEL"),
				"stat_3_value":                           msg("LANDING_STAT_3_VALUE"),
				"stat_3_label":                           msg("LANDING_STAT_3_LABEL"),
				"stat_3_hint":                            msg("LANDING_STAT_3_HINT"),
				"flow_title":                             msg("LANDING_FLOW_TITLE"),
				"flow_subtitle":                          msg("LANDING_FLOW_SUBTITLE"),
				"flow_1_title":                           msg("LANDING_FLOW_1_TITLE"),
				"flow_1_body":                            msg("LANDING_FLOW_1_BODY"),
				"flow_2_title":                           msg("LANDING_FLOW_2_TITLE"),
				"flow_2_body":                            msg("LANDING_FLOW_2_BODY"),
				"flow_3_title":                           msg("LANDING_FLOW_3_TITLE"),
				"flow_3_body":                            msg("LANDING_FLOW_3_BODY"),
				"flow_4_title":                           msg("LANDING_FLOW_4_TITLE"),
				"flow_4_body":                            msg("LANDING_FLOW_4_BODY"),
				"why_title":                              msg("LANDING_WHY_TITLE"),
				"why_subtitle":                           msg("LANDING_WHY_SUBTITLE"),
				"why_1_title":                            msg("LANDING_WHY_1_TITLE"),
				"why_1_body":                             msg("LANDING_WHY_1_BODY"),
				"why_2_title":                            msg("LANDING_WHY_2_TITLE"),
				"why_2_body":                             msg("LANDING_WHY_2_BODY"),
				"why_3_title":                            msg("LANDING_WHY_3_TITLE"),
				"why_3_body":                             msg("LANDING_WHY_3_BODY"),
				"why_4_title":                            msg("LANDING_WHY_4_TITLE"),
				"why_4_body":                             msg("LANDING_WHY_4_BODY"),
				"why_5_title":                            msg("LANDING_WHY_5_TITLE"),
				"why_5_body":                             msg("LANDING_WHY_5_BODY"),
				"why_6_title":                            msg("LANDING_WHY_6_TITLE"),
				"why_6_body":                             msg("LANDING_WHY_6_BODY"),
				"why_7_title":                            msg("LANDING_WHY_7_TITLE"),
				"why_7_body":                             msg("LANDING_WHY_7_BODY"),
				"why_8_title":                            msg("LANDING_WHY_8_TITLE"),
				"why_8_body":                             msg("LANDING_WHY_8_BODY"),
				"why_9_title":                            msg("LANDING_WHY_9_TITLE"),
				"why_9_body":                             msg("LANDING_WHY_9_BODY"),
				"why_10_title":                           msg("LANDING_WHY_10_TITLE"),
				"why_10_body":                            msg("LANDING_WHY_10_BODY"),
				"why_11_title":                           msg("LANDING_WHY_11_TITLE"),
				"why_11_body":                            msg("LANDING_WHY_11_BODY"),
				"why_12_title":                           msg("LANDING_WHY_12_TITLE"),
				"why_12_body":                            msg("LANDING_WHY_12_BODY"),
				"use_title":                              msg("LANDING_USE_TITLE"),
				"use_subtitle":                           msg("LANDING_USE_SUBTITLE"),
				"use_1_title":                            msg("LANDING_USE_1_TITLE"),
				"use_1_body":                             msg("LANDING_USE_1_BODY"),
				"use_2_title":                            msg("LANDING_USE_2_TITLE"),
				"use_2_body":                             msg("LANDING_USE_2_BODY"),
				"use_3_title":                            msg("LANDING_USE_3_TITLE"),
				"use_3_body":                             msg("LANDING_USE_3_BODY"),
				"install_subtitle":                       msg("LANDING_INSTALL_SUBTITLE"),
				"demo_cost_hint":                         msg("LANDING_DEMO_COST_HINT"),
				"privacy_title":                          msg("LEGAL_PRIVACY_TITLE"),
				"terms_title":                            msg("LEGAL_TERMS_TITLE"),
				"updated_prefix":                         msg("LEGAL_UPDATED_PREFIX"),
				"updated_date":                           msg("LEGAL_UPDATED_DATE"),
				"link_privacy":                           msg("LEGAL_LINK_PRIVACY"),
				"link_terms":                             msg("LEGAL_LINK_TERMS"),
				"link_home":                              msg("LEGAL_LINK_HOME"),
				"meta_sep":                               msg("DASHBOARD_META_SEP"),
				"login_phrase_or":                        msg("CLI_LOGIN_PHRASE_OR"),
				"login_phrase_comma":                     msg("CLI_LOGIN_PHRASE_COMMA"),
				"dialog_cancel":                          msg("DIALOG_CANCEL"),
				"skeleton_metric_plan_label":             msg("DASHBOARD_METRIC_PLAN"),
				"skeleton_metric_credits_label":          msg("DASHBOARD_METRIC_CREDITS"),
				"skeleton_metric_remaining_label":        msg("DASHBOARD_METRIC_REMAINING"),
				"skeleton_metric_tokens_saved_label":     msg("DASHBOARD_METRIC_TOKENS_SAVED"),
				"skeleton_metric_tab_label":              msg("DASHBOARD_METRIC_TAB"),
				"skeleton_metric_lines_added_label":      msg("DASHBOARD_METRIC_LINES_ADDED"),
				"skeleton_metric_lines_deleted_label":    msg("DASHBOARD_METRIC_LINES_DELETED"),
				"skeleton_chart_token_series_title":      msg("DASHBOARD_CHART_TOKEN_SERIES"),
				"skeleton_chart_models_title":            msg("DASHBOARD_CHART_MODELS"),
				"skeleton_chart_outcomes_title":          msg("DASHBOARD_CHART_OUTCOMES"),
				"skeleton_chart_modes_title":             msg("DASHBOARD_CHART_MODES"),
				"skeleton_page_eyebrow":                  msg("DASHBOARD_PAGE_EYEBROW"),
				"skeleton_traces_title":                  msg("DASHBOARD_TRACES_TITLE"),
				"skeleton_receipts_title":                msg("DASHBOARD_RECEIPTS_TITLE"),
				"skeleton_traces_col_when":               msg("EVENTS_COL_WHEN"),
				"skeleton_traces_col_model":              msg("EVENTS_COL_MODEL"),
				"skeleton_traces_col_mode":               msg("EVENTS_COL_MODE"),
				"skeleton_traces_col_tokens":             msg("EVENTS_COL_TOKENS"),
				"skeleton_traces_col_latency":            msg("EVENTS_COL_LATENCY"),
				"skeleton_traces_col_view":               msg("EVENTS_COL_VIEW"),
				"skeleton_traces_date_range":             msg("EVENTS_DATE_RANGE_PLACEHOLDER"),
				"skeleton_traces_date_range_desc":        msg("EVENTS_DATE_RANGE_DESC"),
				"skeleton_traces_search":                 msg("EVENTS_SEARCH"),
				"skeleton_traces_search_desc":            msg("EVENTS_SEARCH_DESC"),
				"skeleton_receipts_col_date":             msg("RECEIPTS_COL_DATE"),
				"skeleton_receipts_col_invoice":          msg("RECEIPTS_COL_INVOICE"),
				"skeleton_receipts_col_status":           msg("RECEIPTS_COL_STATUS"),
				"skeleton_receipts_col_total":            msg("RECEIPTS_COL_TOTAL"),
				"skeleton_receipts_col_view":             msg("RECEIPTS_COL_VIEW"),
				"skeleton_receipts_search":               msg("RECEIPTS_SEARCH"),
				"skeleton_receipts_search_desc":          msg("RECEIPTS_SEARCH_DESC"),
				"skeleton_receipts_sync_label":           msg("ACTION:RECEIPTS_SYNC"),
				"skeleton_enterprise_title":              msg("ENTERPRISE_ME_TITLE"),
				"skeleton_enterprise_col_company":        msg("ENTERPRISE_ME_COL_COMPANY"),
				"skeleton_enterprise_col_status":         msg("ENTERPRISE_ME_COL_STATUS"),
				"skeleton_enterprise_col_requested":      msg("ENTERPRISE_ME_COL_REQUESTED"),
				"skeleton_enterprise_col_offered":        msg("ENTERPRISE_ME_COL_OFFERED"),
				"skeleton_enterprise_col_created":        msg("ENTERPRISE_ME_COL_CREATED"),
				"skeleton_enterprise_filter_status":      msg("ENTERPRISE_ME_FILTER_STATUS"),
				"skeleton_enterprise_filter_status_desc": msg("ENTERPRISE_ME_FILTER_STATUS_DESC"),
				"skeleton_enterprise_search":             msg("ENTERPRISE_ME_SEARCH"),
				"skeleton_enterprise_search_desc":        msg("ENTERPRISE_ME_SEARCH_DESC"),
				"skeleton_team_workspaces_title":         msg("WORKSPACE_LIST_TITLE"),
				"skeleton_team_members_title":            msg("WORKSPACE_MEMBERS_TITLE"),
				"skeleton_team_invites_title":            msg("WORKSPACE_INVITES_TITLE"),
				"skeleton_receipt_col_description":       msg("RECEIPT_COL_DESCRIPTION"),
				"skeleton_receipt_col_sku":               msg("RECEIPT_COL_SKU"),
				"skeleton_receipt_col_qty":               msg("RECEIPT_COL_QTY"),
				"skeleton_receipt_col_unit":              msg("RECEIPT_COL_UNIT"),
				"skeleton_receipt_col_amount":            msg("RECEIPT_COL_AMOUNT"),
				"skeleton_receipt_section_bill_to":       msg("RECEIPT_SECTION_BILL_TO"),
				"skeleton_receipt_section_period":        msg("RECEIPT_SECTION_PERIOD"),
				"skeleton_receipt_section_amount":        msg("RECEIPT_SECTION_AMOUNT"),
				"skeleton_receipt_section_status":        msg("RECEIPT_SECTION_STATUS"),
				"skeleton_receipt_section_payment":       msg("RECEIPT_SECTION_PAYMENT"),
				"skeleton_receipt_footer":                msg("RECEIPT_FOOTER"),
				"skeleton_settings_page_title":           msg("PREFERENCES_PAGE_TITLE"),
				"skeleton_settings_page_description":     msg("PREFERENCES_PAGE_DESCRIPTION"),
				"skeleton_settings_tier_title":           msg("PREFERENCES_TIER_TITLE"),
				"skeleton_settings_deep_label":           msg("PREFERENCES_DEEP_LABEL"),
				"skeleton_settings_cli_title":            msg("PREFERENCES_CLI_TITLE"),
				"skeleton_settings_keys_title":           msg("PREFERENCES_KEYS_TITLE"),
				"skeleton_settings_save_label":           msg("ACTION:PREFERENCES_SAVE"),
				"skeleton_settings_back_label":           msg("PREFERENCES_BACK_LABEL"),
				"skeleton_settings_account_title":        msg("PREFERENCES_ACCOUNT_TITLE"),
				"skeleton_settings_auth_provider_prefix": msg("PREFERENCES_AUTH_PROVIDER_PREFIX"),
				"skeleton_settings_link_hint":            msg("PREFERENCES_LINK_HINT"),
				"skeleton_settings_unlink_label":         msg("ACTION:AUTH_UNLINK"),
				"skeleton_settings_row_actions_label":    msg("TABLE_ROW_ACTIONS"),
				"sign_out_action_label":                  msg("ACTION:SIGN_OUT"),
				"sign_out_pending_label":                 msg("PENDING:SIGN_OUT"),
				"seo_title_template":                     msg("SEO_TITLE_TEMPLATE"),
				"seo_default_title":                      msg("SEO_DEFAULT_TITLE"),
				"seo_default_description":                msg("SEO_DEFAULT_DESCRIPTION"),
				"seo_og_site_name":                       msg("SEO_OG_SITE_NAME"),
				"seo_og_type":                            msg("SEO_OG_TYPE"),
				"seo_twitter_card":                       msg("SEO_TWITTER_CARD"),
				"seo_robots_index":                       msg("SEO_ROBOTS_INDEX"),
				"seo_robots_noindex":                     msg("SEO_ROBOTS_NOINDEX"),
				"page_404_code":                          msg("PAGE_404_CODE"),
				"page_404_title":                         msg("PAGE_404_TITLE"),
				"page_404_heading":                       msg("PAGE_404_HEADING"),
				"page_404_body":                          msg("PAGE_404_BODY"),
				"page_404_home_cta":                      msg("PAGE_404_HOME_CTA"),
				"page_404_docs_cta":                      msg("PAGE_404_DOCS_CTA"),
				"page_404_docs_href":                     msg("PAGE_404_DOCS_HREF"),
				"page_error_title":                       msg("PAGE_ERROR_TITLE"),
				"page_error_heading":                     msg("PAGE_ERROR_HEADING"),
				"page_error_body":                        msg("PAGE_ERROR_BODY"),
				"page_error_retry_cta":                   msg("PAGE_ERROR_RETRY_CTA"),
				"page_error_home_cta":                    msg("PAGE_ERROR_HOME_CTA"),
				"admin_page_404_title":                   msg("ADMIN_PAGE_404_TITLE"),
				"admin_page_404_heading":                 msg("ADMIN_PAGE_404_HEADING"),
				"admin_page_404_body":                    msg("ADMIN_PAGE_404_BODY"),
				"admin_page_404_home_cta":                msg("ADMIN_PAGE_404_HOME_CTA"),
				"admin_page_error_title":                 msg("ADMIN_PAGE_ERROR_TITLE"),
				"admin_page_error_heading":               msg("ADMIN_PAGE_ERROR_HEADING"),
				"admin_page_error_body":                  msg("ADMIN_PAGE_ERROR_BODY"),
				"admin_page_error_retry_cta":             msg("ADMIN_PAGE_ERROR_RETRY_CTA"),
				"admin_page_error_home_cta":              msg("ADMIN_PAGE_ERROR_HOME_CTA"),
				"admin_seo_default_title":                msg("ADMIN_SEO_DEFAULT_TITLE"),
				"admin_seo_default_description":          msg("ADMIN_SEO_DEFAULT_DESCRIPTION"),
				"admin_seo_robots":                       msg("ADMIN_SEO_ROBOTS"),
				"contact_page_title":                     msg("CONTACT_PAGE_TITLE"),
				"contact_page_heading":                   msg("CONTACT_PAGE_HEADING"),
				"contact_page_body":                      msg("CONTACT_PAGE_BODY"),
				"contact_meta_description":               msg("CONTACT_META_DESCRIPTION"),
				"contact_email_label":                    msg("CONTACT_EMAIL_LABEL"),
				"contact_open_mail_cta":                  msg("CONTACT_OPEN_MAIL_CTA"),
				"contact_topics_heading":                 msg("CONTACT_TOPICS_HEADING"),
				"contact_topic_general_label":            msg("CONTACT_TOPIC_GENERAL_LABEL"),
				"contact_topic_general_desc":             msg("CONTACT_TOPIC_GENERAL_DESC"),
				"contact_topic_general_subject":          msg("CONTACT_TOPIC_GENERAL_SUBJECT"),
				"contact_topic_general_body":             msg("CONTACT_TOPIC_GENERAL_BODY"),
				"contact_topic_billing_label":            msg("CONTACT_TOPIC_BILLING_LABEL"),
				"contact_topic_billing_desc":             msg("CONTACT_TOPIC_BILLING_DESC"),
				"contact_topic_billing_subject":          msg("CONTACT_TOPIC_BILLING_SUBJECT"),
				"contact_topic_billing_body":             msg("CONTACT_TOPIC_BILLING_BODY"),
				"contact_topic_sales_label":              msg("CONTACT_TOPIC_SALES_LABEL"),
				"contact_topic_sales_desc":               msg("CONTACT_TOPIC_SALES_DESC"),
				"contact_topic_sales_subject":            msg("CONTACT_TOPIC_SALES_SUBJECT"),
				"contact_topic_sales_body":               msg("CONTACT_TOPIC_SALES_BODY"),
				"contact_topic_security_label":           msg("CONTACT_TOPIC_SECURITY_LABEL"),
				"contact_topic_security_desc":            msg("CONTACT_TOPIC_SECURITY_DESC"),
				"contact_topic_security_subject":         msg("CONTACT_TOPIC_SECURITY_SUBJECT"),
				"contact_topic_security_body":            msg("CONTACT_TOPIC_SECURITY_BODY"),
				"checkout_success_title":                 msg("CHECKOUT_SUCCESS_TITLE"),
				"checkout_success_body":                  msg("CHECKOUT_SUCCESS_BODY"),
				"checkout_success_dashboard_label":       msg("CHECKOUT_SUCCESS_DASHBOARD_LABEL"),
				"checkout_success_receipts_label":        msg("CHECKOUT_SUCCESS_RECEIPTS_LABEL"),
				"checkout_success_toast":                 msg("CHECKOUT_SUCCESS_TOAST"),
			},
			"privacy_sections":             privacySections,
			"terms_sections":               termsSections,
			"privacy_section_count":        len(privacySections),
			"terms_section_count":          len(termsSections),
			"support_email":                strings.TrimSpace(supportEmail),
			"auth_not_signed_in_message":   msg("AUTH_NOT_SIGNED_IN"),
			"default_page_size":            defaultPageSize,
			"plan_card_count":              planCardCount,
			"plan_subscription_card_count": planSubscriptionCardCount,
			"plan_topup_card_count":        planTopupCardCount,
			"dialog_close_label":           msg("DIALOG_CLOSE"),
			"dialog_cancel":                msg("DIALOG_CANCEL"),
			"admin_forbidden_page":         msg("ADMIN_FORBIDDEN_PAGE"),
			"admin_credentials_revoked":    msg("AUTH_CREDENTIALS_REVOKED"),
			"admin_bootstrap_required":     msg("ADMIN_BOOTSTRAP_REQUIRED"),
			"local":                        localchrome.FromMessages(msg),
			"cli": map[string]string{
				"issue_action_label":                     msg("ACTION:API_KEY_ISSUE"),
				"issue_pending_label":                    msg("PENDING:API_KEY_ISSUE"),
				"issue_retry_action_label":               msg("ACTION:API_KEY_ISSUE_RETRY"),
				"issue_another_action_label":             msg("ACTION:API_KEY_ISSUE_ANOTHER"),
				"copy_action_label":                      msg("ACTION:API_KEY_COPY"),
				"copy_pending_label":                     msg("PENDING:API_KEY_COPY"),
				"copied_action_label":                    msg("ACTION:API_KEY_COPIED"),
				"eyebrow":                                msg("CLI_AUTH_EYEBROW"),
				"title":                                  msg("CLI_AUTH_TITLE"),
				"body":                                   msg("CLI_AUTH_BODY"),
				"issue_failed_message":                   msg("CLI_AUTH_ISSUE_FAILED"),
				"footer":                                 msg("CLI_AUTH_FOOTER"),
				"copied_reset_ms":                        msg("CLI_AUTH_COPIED_RESET_MS"),
				"login_sign_in_fmt":                      msg("CLI_LOGIN_SIGN_IN_FMT"),
				"login_opening_browser":                  msg("CLI_LOGIN_OPENING_BROWSER"),
				"login_paste_key":                        msg("CLI_LOGIN_PASTE_KEY"),
				"login_key_required":                     msg("CLI_LOGIN_KEY_REQUIRED"),
				"login_success":                          msg("CLI_LOGIN_SUCCESS"),
				"logout_success":                         msg("CLI_LOGOUT_SUCCESS"),
				"logout_already":                         msg("CLI_LOGOUT_ALREADY"),
				"chrome_unavailable":                     msg("CLI_CHROME_UNAVAILABLE"),
				"browser_unsupported_fmt":                msg("CLI_BROWSER_UNSUPPORTED_FMT"),
				"status_not_logged_in":                   msg("CLI_STATUS_NOT_LOGGED_IN"),
				"login_phrase_or":                        msg("CLI_LOGIN_PHRASE_OR"),
				"login_phrase_comma":                     msg("CLI_LOGIN_PHRASE_COMMA"),
				"login_phrase_comma_or":                  msg("CLI_LOGIN_PHRASE_COMMA_OR"),
				"setup_endpoint_fmt":                     msg("CLI_SETUP_ENDPOINT_FMT"),
				"setup_none_found":                       msg("CLI_SETUP_NONE_FOUND"),
				"setup_updated_header":                   msg("CLI_SETUP_UPDATED_HEADER"),
				"setup_shell_header":                     msg("CLI_SETUP_SHELL_HEADER"),
				"setup_jetbrains_hint":                   msg("CLI_SETUP_JETBRAINS_HINT"),
				"setup_api_endpoint_fmt":                 msg("CLI_SETUP_API_ENDPOINT_FMT"),
				"setup_next_header":                      msg("CLI_SETUP_NEXT_HEADER"),
				"setup_step_start":                       msg("CLI_SETUP_STEP_START"),
				"setup_step_restart":                     msg("CLI_SETUP_STEP_RESTART"),
				"setup_step_login":                       msg("CLI_SETUP_STEP_LOGIN"),
				"setup_step_dashboard_fmt":               msg("CLI_SETUP_STEP_DASHBOARD_FMT"),
				"setup_optional_tls":                     msg("CLI_SETUP_OPTIONAL_TLS"),
				"setup_tls_then":                         msg("CLI_SETUP_TLS_THEN"),
				"setup_tls_generated_fmt":                msg("CLI_SETUP_TLS_GENERATED_FMT"),
				"setup_tls_cert_fmt":                     msg("CLI_SETUP_TLS_CERT_FMT"),
				"setup_tls_key_fmt":                      msg("CLI_SETUP_TLS_KEY_FMT"),
				"setup_tls_key_path_fmt":                 msg("CLI_SETUP_TLS_KEY_PATH_FMT"),
				"setup_shell_openai_fmt":                 msg("CLI_SETUP_SHELL_OPENAI_FMT"),
				"setup_shell_anthropic_fmt":              msg("CLI_SETUP_SHELL_ANTHROPIC_FMT"),
				"setup_tls_start":                        msg("CLI_SETUP_TLS_START"),
				"setup_tls_point_ide":                    msg("CLI_SETUP_TLS_POINT_IDE"),
				"setup_tls_env_required":                 msg("CLI_SETUP_TLS_ENV_REQUIRED"),
				"setup_tls_days_invalid":                 msg("CLI_SETUP_TLS_DAYS_INVALID"),
				"pow_client_required":                    msg("CLI_POW_CLIENT_REQUIRED"),
				"pow_428_missing":                        msg("CLI_POW_428_MISSING"),
				"pow_solve_failed":                       msg("CLI_POW_SOLVE_FAILED"),
				"pow_parse_failed_fmt":                   msg("CLI_POW_PARSE_FAILED_FMT"),
				"setup_wrote_fmt":                        msg("CLI_SETUP_WROTE_FMT"),
				"setup_product_cursor":                   msg("CLI_SETUP_PRODUCT_CURSOR"),
				"setup_product_vscode":                   msg("CLI_SETUP_PRODUCT_VSCODE"),
				"setup_product_windsurf":                 msg("CLI_SETUP_PRODUCT_WINDSURF"),
				"setup_product_continue":                 msg("CLI_SETUP_PRODUCT_CONTINUE"),
				"setup_product_zed":                      msg("CLI_SETUP_PRODUCT_ZED"),
				"setup_product_jetbrains":                msg("CLI_SETUP_PRODUCT_JETBRAINS"),
				"setup_continue_no_model":                msg("CLI_SETUP_CONTINUE_NO_MODEL"),
				"start_running_fmt":                      msg("CLI_START_RUNNING_FMT"),
				"start_dashboard_fmt":                    msg("CLI_START_DASHBOARD_FMT"),
				"start_mode_fmt":                         msg("CLI_START_MODE_FMT"),
				"start_point_ide_fmt":                    msg("CLI_START_POINT_IDE_FMT"),
				"start_rules_fmt":                        msg("CLI_START_RULES_FMT"),
				"start_stopped":                          msg("CLI_START_STOPPED"),
				"err_fmt":                                msg("CLI_ERR_FMT"),
				"proxy_failed_fmt":                       msg("CLI_PROXY_FAILED_FMT"),
				"main_err_fmt":                           msg("CLI_MAIN_ERR_FMT"),
				"daemon_unsupported_fmt":                 msg("CLI_DAEMON_UNSUPPORTED_FMT"),
				"daemon_launchd_installed_fmt":           msg("CLI_DAEMON_LAUNCHD_INSTALLED_FMT"),
				"daemon_launchd_missing":                 msg("CLI_DAEMON_LAUNCHD_MISSING"),
				"daemon_systemd_installed_fmt":           msg("CLI_DAEMON_SYSTEMD_INSTALLED_FMT"),
				"daemon_systemd_missing":                 msg("CLI_DAEMON_SYSTEMD_MISSING"),
				"daemon_windows_missing":                 msg("CLI_DAEMON_WINDOWS_MISSING"),
				"daemon_launchd_ok_fmt":                  msg("CLI_DAEMON_LAUNCHD_OK_FMT"),
				"daemon_launchd_hint":                    msg("CLI_DAEMON_LAUNCHD_HINT"),
				"daemon_launchd_removed":                 msg("CLI_DAEMON_LAUNCHD_REMOVED"),
				"daemon_systemd_ok_fmt":                  msg("CLI_DAEMON_SYSTEMD_OK_FMT"),
				"daemon_systemd_removed":                 msg("CLI_DAEMON_SYSTEMD_REMOVED"),
				"daemon_windows_ok":                      msg("CLI_DAEMON_WINDOWS_OK"),
				"daemon_windows_removed":                 msg("CLI_DAEMON_WINDOWS_REMOVED"),
				"telemetry_enabled":                      msg("CLI_TELEMETRY_ENABLED"),
				"telemetry_disable_hint":                 msg("CLI_TELEMETRY_DISABLE_HINT"),
				"telemetry_env_hint":                     msg("CLI_TELEMETRY_ENV_HINT"),
				"telemetry_disabled":                     msg("CLI_TELEMETRY_DISABLED"),
				"telemetry_enable_hint":                  msg("CLI_TELEMETRY_ENABLE_HINT"),
				"telemetry_disabled_ok":                  msg("CLI_TELEMETRY_DISABLED_OK"),
				"telemetry_enabled_ok":                   msg("CLI_TELEMETRY_ENABLED_OK"),
				"autostart_enabled":                      msg("CLI_AUTOSTART_ENABLED"),
				"autostart_disabled":                     msg("CLI_AUTOSTART_DISABLED"),
				"autostart_unset":                        msg("CLI_AUTOSTART_UNSET"),
				"autostart_enable_hint":                  msg("CLI_AUTOSTART_ENABLE_HINT"),
				"autostart_disable_hint":                 msg("CLI_AUTOSTART_DISABLE_HINT"),
				"autostart_enabled_ok":                   msg("CLI_AUTOSTART_ENABLED_OK"),
				"autostart_disabled_ok":                  msg("CLI_AUTOSTART_DISABLED_OK"),
				"autostart_daemon_hint":                  msg("CLI_AUTOSTART_DAEMON_HINT"),
				"autostart_daemon_skipped_off":           msg("CLI_AUTOSTART_DAEMON_SKIPPED_OFF"),
				"autostart_daemon_skipped_unset":         msg("CLI_AUTOSTART_DAEMON_SKIPPED_UNSET"),
				"autostart_skipped_managed":              msg("CLI_AUTOSTART_SKIPPED_MANAGED"),
				"autostart_skipped_dnt":                  msg("CLI_AUTOSTART_SKIPPED_DNT"),
				"autostart_managed_off_hint":             msg("CLI_AUTOSTART_MANAGED_OFF_HINT"),
				"autostart_sync_daemon_ok":               msg("CLI_AUTOSTART_SYNC_DAEMON_OK"),
				"default_auto_start_with_ide":            msg("DEFAULT_AUTO_START_WITH_IDE"),
				"autostart_pref_poll_ms":                 msg("CLI_AUTOSTART_PREF_POLL_MS"),
				"autostart_enforcer_stopped":             msg("CLI_AUTOSTART_ENFORCER_STOPPED"),
				"autostart_pref_poll_min_ms":             msg("AUTOSTART_PREF_POLL_MIN_MS"),
				"autostart_pref_poll_max_ms":             msg("AUTOSTART_PREF_POLL_MAX_MS"),
				"autostart_timeout_min_ms":               msg("AUTOSTART_TIMEOUT_MIN_MS"),
				"autostart_timeout_max_ms":               msg("AUTOSTART_TIMEOUT_MAX_MS"),
				"daemon_restart_sec":                     msg("CLI_DAEMON_RESTART_SEC"),
				"daemon_restart_min_sec":                 msg("DAEMON_RESTART_MIN_SEC"),
				"daemon_restart_max_sec":                 msg("DAEMON_RESTART_MAX_SEC"),
				"stop_on_disable_ok":                     msg("CLI_STOP_ON_DISABLE_OK"),
				"proxy_health_url":                       msg("IDE_PROXY_HEALTH_URL"),
				"proxy_shutdown_url":                     msg("IDE_PROXY_SHUTDOWN_URL"),
				"proxy_health_timeout_ms":                msg("CLI_PROXY_HEALTH_TIMEOUT_MS"),
				"proxy_shutdown_timeout_ms":              msg("CLI_PROXY_SHUTDOWN_TIMEOUT_MS"),
				"http_shutdown_timeout_ms":               msg("CLI_HTTP_SHUTDOWN_TIMEOUT_MS"),
				"proxy_fallback_uncompressed":            msg("CLI_PROXY_FALLBACK_UNCOMPRESSED"),
				"proxy_active_file_protection":           msg("PROXY_ACTIVE_FILE_PROTECTION"),
				"stop_ok":                                msg("CLI_STOP_OK"),
				"stop_failed_fmt":                        msg("CLI_STOP_FAILED_FMT"),
				"stop_url_missing":                       msg("CLI_STOP_URL_MISSING"),
				"config_get_autostart_unset":             msg("CLI_CONFIG_GET_AUTOSTART_UNSET"),
				"config_get_autostart_fmt":               msg("CLI_CONFIG_GET_AUTOSTART_FMT"),
				"compress_file_required":                 msg("CLI_COMPRESS_FILE_REQUIRED"),
				"compress_mode_required":                 msg("CLI_COMPRESS_MODE_REQUIRED"),
				"compress_mode_invalid":                  msg("CLI_COMPRESS_MODE_INVALID"),
				"treesitter_required":                    msg("CLI_TREESITTER_REQUIRED"),
				"compress_deep_prefs_required":           msg("CLI_COMPRESS_DEEP_PREFS_REQUIRED"),
				"compress_deep_result_fmt":               msg("CLI_COMPRESS_DEEP_RESULT_FMT"),
				"compress_wrote_fmt":                     msg("CLI_COMPRESS_WROTE_FMT"),
				"stats_live_header":                      msg("CLI_STATS_LIVE_HEADER"),
				"stats_live_offline_fmt":                 msg("CLI_STATS_LIVE_OFFLINE_FMT"),
				"stats_url_fmt":                          msg("CLI_STATS_URL_FMT"),
				"stats_url_missing":                      msg("CLI_STATS_URL_MISSING"),
				"stats_sqlite_today_fmt":                 msg("CLI_STATS_SQLITE_TODAY_FMT"),
				"stats_sqlite_series_header":             msg("CLI_STATS_SQLITE_SERIES_HEADER"),
				"stats_sqlite_series_row_fmt":            msg("CLI_STATS_SQLITE_SERIES_ROW_FMT"),
				"stats_tui_tip":                          msg("CLI_STATS_TUI_TIP"),
				"stats_deep_status_fmt":                  msg("CLI_STATS_DEEP_STATUS_FMT"),
				"stats_deep_stage_fmt":                   msg("CLI_STATS_DEEP_STAGE_FMT"),
				"stats_last_request_fmt":                 msg("CLI_STATS_LAST_REQUEST_FMT"),
				"stats_door_fmt":                         msg("CLI_STATS_DOOR_FMT"),
				"stats_dashboard_tip_fmt":                msg("CLI_STATS_DASHBOARD_TIP_FMT"),
				"status_api_fmt":                         msg("CLI_STATUS_API_FMT"),
				"quota_exhausted_title":                  msg("CLI_QUOTA_EXHAUSTED_TITLE"),
				"quota_exhausted_body":                   msg("CLI_QUOTA_EXHAUSTED_BODY"),
				"quota_upgrade_hint_fmt":                 msg("CLI_QUOTA_UPGRADE_HINT_FMT"),
				"quota_upgrade_opening":                  msg("CLI_QUOTA_UPGRADE_OPENING"),
				"quota_upgrade_url_missing":              msg("CLI_QUOTA_UPGRADE_URL_MISSING"),
				"deep_bootstrap_reqs":                    msg("CLI_DEEP_BOOTSTRAP_REQS"),
				"deep_bootstrap_pip":                     msg("CLI_DEEP_BOOTSTRAP_PIP"),
				"deep_requirements_missing":              msg("CLI_DEEP_REQUIREMENTS_MISSING"),
				"deep_auto_install":                      msg("CLI_DEEP_AUTO_INSTALL"),
				"deep_bin_env_missing_fmt":               msg("CLI_DEEP_BIN_ENV_MISSING_FMT"),
				"deep_bin_missing":                       msg("CLI_DEEP_BIN_MISSING"),
				"deep_py_env_missing_fmt":                msg("CLI_DEEP_PY_ENV_MISSING_FMT"),
				"deep_py_missing":                        msg("CLI_DEEP_PY_MISSING"),
				"deep_llm_missing_fmt":                   msg("CLI_DEEP_LLM_MISSING_FMT"),
				"deep_pip_failed":                        msg("CLI_DEEP_PIP_FAILED"),
				"deep_target_required":                   msg("CLI_DEEP_TARGET_REQUIRED"),
				"deep_engine_required":                   msg("CLI_DEEP_ENGINE_REQUIRED"),
				"deep_question_required":                 msg("CLI_DEEP_QUESTION_REQUIRED"),
				"deep_optimize_fmt":                      msg("CLI_DEEP_OPTIMIZE_FMT"),
				"deep_timeout":                           msg("CLI_DEEP_TIMEOUT"),
				"deep_parse_fmt":                         msg("CLI_DEEP_PARSE_FMT"),
				"proxy_deep_failed_fmt":                  msg("CLI_PROXY_DEEP_FAILED_FMT"),
				"proxy_live_deep_mode_fmt":               msg("CLI_PROXY_LIVE_DEEP_MODE_FMT"),
				"proxy_live_deep_enabled_fmt":            msg("CLI_PROXY_LIVE_DEEP_ENABLED_FMT"),
				"proxy_deep_compact_stub":                msg("CLI_PROXY_DEEP_COMPACT_STUB"),
				"proxy_deep_chrome_required":             msg("CLI_PROXY_DEEP_CHROME_REQUIRED"),
				"proxy_deep_prefs_required":              msg("CLI_PROXY_DEEP_PREFS_REQUIRED"),
				"proxy_deep_skipped_min_fmt":             msg("CLI_PROXY_DEEP_SKIPPED_MIN_FMT"),
				"proxy_deep_skipped_stream":              msg("CLI_PROXY_DEEP_SKIPPED_STREAM"),
				"proxy_deep_oom_skipped":                 msg("CLI_PROXY_DEEP_OOM_SKIPPED"),
				"proxy_deep_runtime_required":            msg("CLI_PROXY_DEEP_RUNTIME_REQUIRED"),
				"proxy_adapter_required":                 msg("CLI_PROXY_ADAPTER_REQUIRED"),
				"proxy_adapter_unknown_dialect_fmt":      msg("CLI_PROXY_ADAPTER_UNKNOWN_DIALECT_FMT"),
				"proxy_adapter_model_required":           msg("CLI_PROXY_ADAPTER_MODEL_REQUIRED"),
				"proxy_adapter_alias_required_fmt":       msg("CLI_PROXY_ADAPTER_ALIAS_REQUIRED_FMT"),
				"proxy_adapter_translate_fmt":            msg("CLI_PROXY_ADAPTER_TRANSLATE_FMT"),
				"proxy_adapter_auth_fmt":                 msg("CLI_PROXY_ADAPTER_AUTH_FMT"),
				"proxy_adapter_response_fmt":             msg("CLI_PROXY_ADAPTER_RESPONSE_FMT"),
				"proxy_adapter_enabled_fmt":              msg("CLI_PROXY_ADAPTER_ENABLED_FMT"),
				"proxy_models_not_synced":                msg("CLI_PROXY_MODELS_NOT_SYNCED"),
				"proxy_models_method":                    msg("CLI_PROXY_MODELS_METHOD"),
				"proxy_err_base_url_double_v1":           msg("CLI_PROXY_ERR_BASE_URL_DOUBLE_V1"),
				"proxy_err_model_not_found_fmt":          msg("CLI_PROXY_ERR_MODEL_NOT_FOUND_FMT"),
				"proxy_err_unknown_model_fmt":            msg("CLI_PROXY_ERR_UNKNOWN_MODEL_FMT"),
				"proxy_err_upstream_auth_fmt":            msg("CLI_PROXY_ERR_UPSTREAM_AUTH_FMT"),
				"proxy_err_upstream_quota_fmt":           msg("CLI_PROXY_ERR_UPSTREAM_QUOTA_FMT"),
				"proxy_err_upstream_unavailable_fmt":     msg("CLI_PROXY_ERR_UPSTREAM_UNAVAILABLE_FMT"),
				"setup_claude_code_block_fmt":            msg("CLI_SETUP_CLAUDE_CODE_BLOCK_FMT"),
				"setup_continue_block_fmt":               msg("CLI_SETUP_CONTINUE_BLOCK_FMT"),
				"setup_vscode_chat_block_fmt":            msg("CLI_SETUP_VSCODE_CHAT_BLOCK_FMT"),
				"proxy_models_upstream_not_found_fmt":    msg("CLI_PROXY_MODELS_UPSTREAM_NOT_FOUND_FMT"),
				"proxy_models_upstream_auth":             msg("CLI_PROXY_MODELS_UPSTREAM_AUTH"),
				"proxy_models_upstream_unsupported_fmt":  msg("CLI_PROXY_MODELS_UPSTREAM_UNSUPPORTED_FMT"),
				"proxy_models_upstream_adapter_required": msg("CLI_PROXY_MODELS_UPSTREAM_ADAPTER_REQUIRED"),
				"proxy_door_openai":                      msg("CLI_PROXY_DOOR_OPENAI"),
				"proxy_door_anthropic":                   msg("CLI_PROXY_DOOR_ANTHROPIC"),
				"prefs_engine_invalid":                   msg("CLI_PREFS_ENGINE_INVALID"),
				"prefs_target_nonneg":                    msg("CLI_PREFS_TARGET_NONNEG"),
				"prefs_tier_required":                    msg("CLI_PREFS_TIER_REQUIRED"),
				"prefs_engine_required":                  msg("CLI_PREFS_ENGINE_REQUIRED"),
				"prefs_target_required":                  msg("CLI_PREFS_TARGET_REQUIRED"),
				"config_get_tier_fmt":                    msg("CLI_CONFIG_GET_TIER_FMT"),
				"config_get_engine_fmt":                  msg("CLI_CONFIG_GET_ENGINE_FMT"),
				"config_get_target_fmt":                  msg("CLI_CONFIG_GET_TARGET_FMT"),
				"config_unknown_key_fmt":                 msg("CLI_CONFIG_UNKNOWN_KEY_FMT"),
				"config_target_positive":                 msg("CLI_CONFIG_TARGET_POSITIVE"),
				"config_saved_fmt":                       msg("CLI_CONFIG_SAVED_FMT"),
				"config_not_logged_in":                   msg("CLI_CONFIG_NOT_LOGGED_IN"),
				"config_sync_failed_fmt":                 msg("CLI_CONFIG_SYNC_FAILED_FMT"),
				"config_synced_fmt":                      msg("CLI_CONFIG_SYNCED_FMT"),
				"help_root_short":                        msg("CLI_HELP_ROOT_SHORT"),
				"help_root_long":                         msg("CLI_HELP_ROOT_LONG"),
				"help_group_everyday":                    msg("CLI_HELP_GROUP_EVERYDAY"),
				"help_group_advanced":                    msg("CLI_HELP_GROUP_ADVANCED"),
				"help_start_short":                       msg("CLI_HELP_START_SHORT"),
				"help_start_long":                        msg("CLI_HELP_START_LONG"),
				"help_start_flag_port":                   msg("CLI_HELP_START_FLAG_PORT"),
				"help_login_short":                       msg("CLI_HELP_LOGIN_SHORT"),
				"help_logout_short":                      msg("CLI_HELP_LOGOUT_SHORT"),
				"help_uninstall_short":                   msg("CLI_HELP_UNINSTALL_SHORT"),
				"help_uninstall_long":                    msg("CLI_HELP_UNINSTALL_LONG"),
				"help_uninstall_flag_keep_data":          msg("CLI_HELP_UNINSTALL_FLAG_KEEP_DATA"),
				"uninstall_starting":                     msg("CLI_UNINSTALL_STARTING"),
				"uninstall_stopped":                      msg("CLI_UNINSTALL_STOPPED"),
				"uninstall_daemon_ok":                    msg("CLI_UNINSTALL_DAEMON_OK"),
				"uninstall_logout_ok":                    msg("CLI_UNINSTALL_LOGOUT_OK"),
				"uninstall_setup_reverted_fmt":           msg("CLI_UNINSTALL_SETUP_REVERTED_FMT"),
				"uninstall_setup_none":                   msg("CLI_UNINSTALL_SETUP_NONE"),
				"uninstall_config_removed_fmt":           msg("CLI_UNINSTALL_CONFIG_REMOVED_FMT"),
				"uninstall_logs_removed":                 msg("CLI_UNINSTALL_LOGS_REMOVED"),
				"uninstall_deep_ok":                      msg("CLI_UNINSTALL_DEEP_OK"),
				"uninstall_deep_skipped":                 msg("CLI_UNINSTALL_DEEP_SKIPPED"),
				"uninstall_sidecar_removed_fmt":          msg("CLI_UNINSTALL_SIDECAR_REMOVED_FMT"),
				"uninstall_binary_removed_fmt":           msg("CLI_UNINSTALL_BINARY_REMOVED_FMT"),
				"uninstall_binary_manual_fmt":            msg("CLI_UNINSTALL_BINARY_MANUAL_FMT"),
				"uninstall_path_removed":                 msg("CLI_UNINSTALL_PATH_REMOVED"),
				"uninstall_done":                         msg("CLI_UNINSTALL_DONE"),
				"uninstall_next_ext":                     msg("CLI_UNINSTALL_NEXT_EXT"),
				"uninstall_next_pkg_brew":                msg("CLI_UNINSTALL_NEXT_PKG_BREW"),
				"uninstall_next_pkg_scoop":               msg("CLI_UNINSTALL_NEXT_PKG_SCOOP"),
				"uninstall_next_pkg_winget":              msg("CLI_UNINSTALL_NEXT_PKG_WINGET"),
				"uninstall_hf_hub_dirs":                  msg("CLI_UNINSTALL_HF_HUB_DIRS"),
				"uninstall_hf_cache_rel":                 msg("CLI_UNINSTALL_HF_CACHE_REL"),
				"uninstall_hf_hub_subdir":                msg("CLI_UNINSTALL_HF_HUB_SUBDIR"),
				"uninstall_home_dirs_rel":                msg("CLI_UNINSTALL_HOME_DIRS_REL"),
				"uninstall_home_dirs_missing":            msg("CLI_UNINSTALL_HOME_DIRS_MISSING"),
				"uninstall_darwin_log_rels":              msg("CLI_UNINSTALL_DARWIN_LOG_RELS"),
				"uninstall_pip_packages":                 msg("CLI_UNINSTALL_PIP_PACKAGES"),
				"uninstall_pip_bins":                     msg("CLI_UNINSTALL_PIP_BINS"),
				"uninstall_python_bins":                  msg("CLI_UNINSTALL_PYTHON_BINS"),
				"uninstall_pip_module":                   msg("CLI_UNINSTALL_PIP_MODULE"),
				"uninstall_sidecar_names":                msg("CLI_UNINSTALL_SIDECAR_NAMES"),
				"uninstall_arp_display_name":             msg("CLI_UNINSTALL_ARP_DISPLAY_NAME"),
				"uninstall_arp_publisher":                msg("CLI_UNINSTALL_ARP_PUBLISHER"),
				"uninstall_arp_reg_key":                  msg("CLI_UNINSTALL_ARP_REG_KEY"),
				"uninstall_arp_removed":                  msg("CLI_UNINSTALL_ARP_REMOVED"),
				"help_status_short":                      msg("CLI_HELP_STATUS_SHORT"),
				"help_status_long":                       msg("CLI_HELP_STATUS_LONG"),
				"help_upgrade_short":                     msg("CLI_HELP_UPGRADE_SHORT"),
				"help_stats_short":                       msg("CLI_HELP_STATS_SHORT"),
				"help_stats_long":                        msg("CLI_HELP_STATS_LONG"),
				"help_stats_flag_tui":                    msg("CLI_HELP_STATS_FLAG_TUI"),
				"help_setup_short":                       msg("CLI_HELP_SETUP_SHORT"),
				"help_setup_long":                        msg("CLI_HELP_SETUP_LONG"),
				"help_setup_flag_tls":                    msg("CLI_HELP_SETUP_FLAG_TLS"),
				"help_version_short":                     msg("CLI_HELP_VERSION_SHORT"),
				"help_daemon_short":                      msg("CLI_HELP_DAEMON_SHORT"),
				"help_daemon_install_short":              msg("CLI_HELP_DAEMON_INSTALL_SHORT"),
				"help_daemon_uninstall_short":            msg("CLI_HELP_DAEMON_UNINSTALL_SHORT"),
				"help_daemon_status_short":               msg("CLI_HELP_DAEMON_STATUS_SHORT"),
				"help_daemon_run_short":                  msg("CLI_HELP_DAEMON_RUN_SHORT"),
				"help_daemon_service_desc":               msg("CLI_HELP_DAEMON_SERVICE_DESC"),
				"help_telemetry_short":                   msg("CLI_HELP_TELEMETRY_SHORT"),
				"help_telemetry_status_short":            msg("CLI_HELP_TELEMETRY_STATUS_SHORT"),
				"help_telemetry_disable_short":           msg("CLI_HELP_TELEMETRY_DISABLE_SHORT"),
				"help_telemetry_enable_short":            msg("CLI_HELP_TELEMETRY_ENABLE_SHORT"),
				"help_autostart_short":                   msg("CLI_HELP_AUTOSTART_SHORT"),
				"help_autostart_status_short":            msg("CLI_HELP_AUTOSTART_STATUS_SHORT"),
				"help_autostart_enable_short":            msg("CLI_HELP_AUTOSTART_ENABLE_SHORT"),
				"help_autostart_disable_short":           msg("CLI_HELP_AUTOSTART_DISABLE_SHORT"),
				"help_stop_short":                        msg("CLI_HELP_STOP_SHORT"),
				"help_tui_short":                         msg("CLI_HELP_TUI_SHORT"),
				"help_tui_long":                          msg("CLI_HELP_TUI_LONG"),
				"help_compress_short":                    msg("CLI_HELP_COMPRESS_SHORT"),
				"help_compress_long":                     msg("CLI_HELP_COMPRESS_LONG"),
				"help_compress_flag_mode":                msg("CLI_HELP_COMPRESS_FLAG_MODE"),
				"help_compress_flag_deep":                msg("CLI_HELP_COMPRESS_FLAG_DEEP"),
				"help_compress_flag_engine":              msg("CLI_HELP_COMPRESS_FLAG_ENGINE"),
				"help_compress_flag_question":            msg("CLI_HELP_COMPRESS_FLAG_QUESTION"),
				"help_compress_flag_target":              msg("CLI_HELP_COMPRESS_FLAG_TARGET"),
				"help_compress_flag_bootstrap":           msg("CLI_HELP_COMPRESS_FLAG_BOOTSTRAP"),
				"help_compress_flag_out":                 msg("CLI_HELP_COMPRESS_FLAG_OUT"),
				"help_config_short":                      msg("CLI_HELP_CONFIG_SHORT"),
				"help_config_get_short":                  msg("CLI_HELP_CONFIG_GET_SHORT"),
				"help_config_set_short":                  msg("CLI_HELP_CONFIG_SET_SHORT"),
				"help_config_sync_short":                 msg("CLI_HELP_CONFIG_SYNC_SHORT"),
			},
		}
		for k, v := range oauthChrome {
			payload[k] = v
		}
		_ = json.NewEncoder(w).Encode(payload)
	}
}
